### ISSUE TITLE
Инвентория - чтение/запись всех данных формы

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#173]
Сохранение данных инвентории работает частично. Нужно проверить и доделать чтение/сохранение всех разделов

О проблемах/неясностях сообщать

Добавить enum для media (он нужен для сохранения медиа различных типов, у нас используется только mtPhoto)

mtUnknown = 0,
    mtPhoto =1,
    mtPhotoPreview = 2,
    mtVideo = 3,
    mtVideoPreview = 4,
    mtAudio = 5,
    mtPDFDocument = 6,
    mtJSONDocument = 7,
    mtBinaryData = 8,
    mtDocument = 9

**Comment by kamabzalov** [comment]
@JSDID план такой:
Проверяем каждую вкладку аккордиона на корректност чтения/сохранения. Проверили General. Если ок, то создаем PR и мерджим и т д с каждой вкладкой (кроме медиа)

**Comment by kamabzalov** [comment]
@JSDID дополнения:
В Разделе "Other" карточки инвентори убрать комбобокс со статусом

В Раздел General добавить логическую группу Audit с чекбоксами

"Data Needs Update" - в пэйлоаде свойство DataNeedsUpdate
"Needs Cleaning" - в пэйлоаде свойство NeedsCleaning
"Ready For Sale" - в пэйлоаде свойство ReadyForSale
"Just Arrived" - в пэйлоаде свойство JustArrived

Дизайн - https://www.figma.com/file/BDg0gIw134tMRsEwMUa3G4/auto-dealer?type=design&node-id=3248-2&mode=design&t=eG0s9EaGtSlIwKaz-4

**Comment by kamabzalov** [comment]
@JSDID внимание!
поле с поисковой иконкой
https://www.figma.com/file/BDg0gIw134tMRsEwMUa3G4/auto-dealer?type=design&node-id=3248-15278&mode=design&t=Eowq6z0x5ALknHQI-0

Суть следующая - при вводе мы ищем в контактах (в фигме по имени компании) компанию, через autocomplete (он есть в prime) подставляем имя компании. 
А при клике на иконку открывается мини таблица контактов - https://www.figma.com/file/BDg0gIw134tMRsEwMUa3G4/auto-dealer?type=design&node-id=3248-15610&mode=design&t=Eowq6z0x5ALknHQI-0

**Comment by kamabzalov** [comment]
@JSDID осталось реализовать поиск с автоподстановкой (который открывает диалог с таблицей аккаунтов)

**Comment by JSDID** [comment]
Так и сейчас работает и горизонтальный и вертикальный перенос
