### ISSUE TITLE
Добавить форму редактирования карточки deal

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#311]
Добавить форму редактирования карточки deal 

Прототип: https://www.figma.com/file/m2birP9cbh1hGTeTtf1qmn/auto-dealer-protos?type=design&node-id=226-2378&mode=design&t=ZoZhoUPKtyJ5Ivsh-4

эндпоинты тут
https://app.swaggerhub.com/apis/ADMSS/admss-web_api/0.1.13

раздел Deals

Верстка и апи делаем в одной задаче (все здесь)

**Comment by kamabzalov** [comment]
@JSDID 

.../ppayments
проапдейчено в сваггере там всё актуально

**Comment by JSDID** [comment]
curl "https://app.admss.com/api/v1/deals/c431758e-7392-454d-8c36-924d31720e0c/ppayments" ^
  -H "Accept: application/json, text/plain, */*" ^
  -H "Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6" ^
  -H "Authorization: Bearer bd276924-82f6-4e5f-99f7-87dce5e2ccc2" ^
  -H "Connection: keep-alive" ^
  -H "Origin: http://localhost:3003" ^
  -H "Referer: http://localhost:3003/" ^
  -H "Sec-Fetch-Dest: empty" ^
  -H "Sec-Fetch-Mode: cors" ^
  -H "Sec-Fetch-Site: cross-site" ^
  -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" ^
  -H ^"sec-ch-ua: ^\^"Chromium^\^";v=^\^"124^\^", ^\^"Google Chrome^\^";v=^\^"124^\^", ^\^"Not-A.Brand^\^";v=^\^"99^\^"^" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H ^"sec-ch-ua-platform: ^\^"Windows^\^"^"![IMG_20240516_154514_620.jpg](https://github.com/kamabzalov/admss-client/assets/102165823/1e342f5a-bad2-4fab-9290-db49499f2f72)

![IMG_20240516_154517_419.jpg](https://github.com/kamabzalov/admss-client/assets/102165823/73275309-8efe-45be-b997-4fbc2eba3d01)

**Comment by JSDID** [comment]
![IMG_20240516_154638_352.jpg](https://github.com/kamabzalov/admss-client/assets/102165823/de377309-9031-47e8-93e8-e2eb82b038b3)

это как было пусто - так и есть

![IMG_20240516_154709_779.jpg](https://github.com/kamabzalov/admss-client/assets/102165823/1674afa6-b75e-4efb-ac11-c6f4f584c6b0)


curl "https://app.admss.com/api/v1/deals/c431758e-7392-454d-8c36-924d31720e0c/ppayments" ^
  -H "Accept: application/json, text/plain, */*" ^
  -H "Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6" ^
  -H "Authorization: Bearer bd276924-82f6-4e5f-99f7-87dce5e2ccc2" ^
  -H "Connection: keep-alive" ^
  -H "Origin: http://localhost:3003" ^
  -H "Referer: http://localhost:3003/" ^
  -H "Sec-Fetch-Dest: empty" ^
  -H "Sec-Fetch-Mode: cors" ^
  -H "Sec-Fetch-Site: cross-site" ^
  -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" ^
  -H ^"sec-ch-ua: ^\^"Chromium^\^";v=^\^"124^\^", ^\^"Google Chrome^\^";v=^\^"124^\^", ^\^"Not-A.Brand^\^";v=^\^"99^\^"^" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H ^"sec-ch-ua-platform: ^\^"Windows^\^"^"

**Comment by kamabzalov** [comment]
В первом приближении реализовано. Другие проблемы будут фикситься в отдельных задачах
