### ISSUE TITLE
Внести изменения в Export to Web

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#383]
Внести изменения в Export to Web

https://www.figma.com/design/BDg0gIw134tMRsEwMUa3G4/auto-dealer?node-id=4224-29081&t=FAYRjH7kOhYzItfE-0

**Comment by JSDID** [comment]
Уточнить хочу по поводу этого: мы вообще убираем сервисы с запросов? Так а для чего они нужны тогда?![IMG_20240527_110110_585.jpg](https://github.com/kamabzalov/admss-client/assets/102165823/7ab68371-4e0a-493e-9c89-9250f7e77782)

**Comment by kamabzalov** [comment]
@JSDID пункт 3 пока не делаем, ждем дизайн

**Comment by kamabzalov** [comment]
@JSDID когда начнете делать, закомментируйте вызов api export. Потому что это реальные данные. Клиент попросил не вызывать api. Когда закончите, не забудьте раскоментировать

**Comment by kamabzalov** [comment]
@JSDID 
для export нашел - [https://app.swaggerhub.com/apis/ADMSS/admss-web_api/0.1.13#/External/get_api_v1_externaluseruidschedule](https://app.swaggerhub.com/apis/ADMSS/admss-web_api/0.1.13#/External/get_api_v1_external__useruid__schedule)

для history - [/api/v1/external/{useruid}/listhistory](https://app.swaggerhub.com/apis/ADMSS/admss-web_api/0.1.13#/External/get_api_v1_external__useruid__listhistory)

Попробуйте эти методы
