### ISSUE TITLE
Для пользователя с правами salesperson показывать только меню Inventory

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#384]
Для пользователя с правами salesperson показывать только меню Inventory

При логине юзер в ответ получает список прав
там есть поле "issalesperson"

**Comment by kamabzalov** [comment]
@JSDID 
Меню сократили, но по прямым ссылкам иду куда хочу

![image](https://github.com/kamabzalov/admss-client/assets/49127222/6f200edc-bff2-4a5a-8f9c-ce3724b8b637)

**Comment by JSDID** [comment]
Вопрос, как https://github.com/kamabzalov/admss-client/issues/430 в этой задаче может быть "Если при создании не указан Stock#" если он required
![photo_2024-06-18_09-23-17](https://github.com/kamabzalov/admss-client/assets/102165823/1b498580-3e4a-48dd-80ba-b804f2ae7b83)

нам валидация не даст его оставить пустым. Или нужно убирать required, или пересматривать логику отработки
