### ISSUE TITLE
Поле stock number. Проверка на уникальность

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#430]
Реализовать надо так: 

1. сделать поле stock необязательным
2. после вводе в поле значения отправлять запрос на проверку наличия такого номера (`/api/v1/inventory/stocknumber`). Если он есть, то помечать поле/форму как нвалидную. Если нет, сохранять сток внутри инвентории

**Comment by JSDID** [comment]
Вопрос, как https://github.com/kamabzalov/admss-client/issues/430 в этой задаче может быть "Если при создании не указан Stock#" если он required

![photo_2024-06-18_09-23-17](https://github.com/kamabzalov/admss-client/assets/102165823/6f485121-76c0-4b63-8416-321aac0f5832)

нам валидация не даст его оставить пустым. Или нужно убирать required, или пересматривать логику отработки

**Comment by kamabzalov** [comment]
@JSDID ответа от бэка

1. Убираем required
2. Если мы ввели сток, то надо отправить запрос на бэк, чтобы понять - уникальный он (сток) или нет.

**Comment by kamabzalov** [comment]
@JSDID обновил описание задачи

**Comment by kamabzalov** [comment]
@JSDID 
Если зайти в созданную инвенторию и менять в ней какую-то инфу, то сразу ругается на уже существующий сток номер

![image](https://github.com/kamabzalov/admss-client/assets/49127222/1fbed1bd-abe8-49b0-b6a7-32b78cd2d9ee)

**Comment by kamabzalov** [comment]
@JSDID 
Если я просто нажму на поле, и не буду его изменять, то мне выдаст ошибку, что такой сток номер уже существует

[Screencast_from_2024-06-22_22-10-47.webm](https://github.com/kamabzalov/admss-client/assets/49127222/a5686019-e3ef-4997-8c82-499b144d8347)

**Comment by kamabzalov** [comment]
@JSDID убирайте ваш предыдущий "костыль" - при существующей инвентории надо делать поле stocknumber disabled

**Comment by kamabzalov** [comment]
@JSDID update (25.06.2024)

Если создавать инвенторию новую, но вписать сток номер какой-то другой инвентории, то мы получим ошибку, что сток номер занят.

После этого если изменить сток номер и сохранить инвенторию, то в запросе на создание у нас прописывается айди ивентории, у которой тот сток номер, что мы пытались изначально использовать. В результате чего у нас НЕ создается новая инвентория, а перезаписывается та, что имела сток номер, который мы изначально ввели.
![image](https://github.com/kamabzalov/admss-client/assets/49127222/0eee344e-9550-48c5-b17a-8db98ce581dd)

А не такой

![image](https://github.com/kamabzalov/admss-client/assets/49127222/905ad43d-87f7-40ed-9361-78057c883467)

**Comment by kamabzalov** [comment]
@JSDID вдогонку:
Вернуть возможность редактирования сток номера (валидировать только при изменении, а еще желательнее, если сток номер изменился от исходного, а не просто событие change вызвалось), при редактировании созданной инвентории. Добавить валидация поля - мин 1 символ, макс 20

**Comment by JSDID** [comment]
https://icecreamapps.com/v/bzvkusr

**Comment by kamabzalov** [comment]
@JSDID ответ от тестировщицы на ваше видео:
"Возможно важна последовательность действий, вот видео как это я повторяю, повторить получается несколько раз. Легче проверять на персоне, где мало инвентории, я использую mobile2 password"

[Uploading Screencast_from_2024-07-02_19-49-44.webm…]()

**Comment by kamabzalov** [comment]
@JSDID я замерджил - посмотрим, что скажет тестировщица
Но я по прежнему наблюдаю излшиние запросы на stocknumber.
Более того - когда я сохраняю инвенторию - то stocknumber зачем-то тоже вызывается

https://monosnap.com/file/6TXM9FX2YN8J4S4OZjZKVtdiSNfDh3
