### ISSUE TITLE
Сохранять данные при создании инвентории в кеше

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#438]
Когда мы создаем инвенторию, у нас есть поля в которых мы можем выбрать другие сущности, в частности контакты. Там же есть кнопочка создания нового контакта, при которой нас открывается форма создания контакта, но если вернуться назад в инвенторию, то все поля очищаются, и получается то, что я вводила до этого мне надо ввести заново. Надо сохранять данные, чтобы они просто так не пропадали и пользователю не надо было делать двойную работу

Думаю, тут store поможет отлично. Создать какое-нибудь свойство типа activeInventory. Это свойство и будет играть роль кэша

**Comment by kamabzalov** [comment]
@JSDID от тестировщицы:

данные должны сохраняться только при создании инвентории. При редактировании уже созданной не надо кэшировать данные, иначе появляется ложное ощущение что какие-то поля сохранились, без нажатия на кнопку save

**Comment by kamabzalov** [comment]
[Screencast from 2024-07-14 22-33-33.webm](https://github.com/user-attachments/assets/46e1bfcd-08e4-46d3-ae57-b1721aa2d3a6)

кэширование при редактировании все еще актуально

**Comment by JSDID** [comment]
Посмотрите еще раз. Только перед тем как проверять сбросте кеш.

**Comment by kamabzalov** [comment]
> Посмотрите еще раз. Только перед тем как проверять сбросте кеш.

@JSDID приложите видео, чтобы я тестировщице показал

**Comment by JSDID** [comment]
https://icecreamapps.com/v/b9t4gxq

**Comment by JSDID** [comment]
Кеш работает как и просили. Только для новой инвентории. Кеш даже не записывается при редактировании (в коде видно)
![photo_2024-07-15_18-24-03](https://github.com/user-attachments/assets/86a15bab-5e86-48c8-b5c6-087387f72cef)
