### ISSUE TITLE
Загрузка прав в контактах

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#468]
При прогрузки прав, аплоудер появляется и на той секции, где мы ничего не загружали. Так же сама картинка прав уходит куда-то вниз. Аплоудер не соответствует дизайну - он должен быть больше

![image](https://github.com/kamabzalov/admss-client/assets/49127222/f4aa50b2-8867-4679-a7ff-bbaa77e1a9fd)

**Comment by kamabzalov** [comment]
@JSDID 

добавлено на бэке

POST /api/v1/contacts/{contactuid}/deletedlicensefront - удаление front части прав
POST /api/v1/contacts/{contactuid}/deletedlicenseback - удаление back части прав

**Comment by kamabzalov** [comment]
@JSDID от тестировщицы:
"У меня все еще удалаяются обе картинки, когда я пытаюсь удалить только одну"

**Comment by JSDID** [comment]
https://icecreamapps.com/v/5m9pqpz

**Comment by kamabzalov** [comment]
@JSDID, от тестировщкика:
на новом устройстве, где адмсс еще не открывался - я добавляю 2 картинки и не могу их удалить.
https://app.admss.com:3002/dashboard/contacts/321ae2e2-2469-4a1e-951a-224d7f6cdcdf?step=4
mobile2 password


Попробуйте в инкогнито или другом браузере (и на другом юзере)

**Comment by JSDID** [comment]
По поводу прав: не удаляет потому что нет разрешения у mobile2. Что сделать? Добавить уведомление об ошибке?
![photo_2024-07-17_17-45-42](https://github.com/user-attachments/assets/f2a7639a-10be-43d3-9719-39f33136c817)

**Comment by kamabzalov** [comment]
@JSDID в любюм случае надо добавить уведомление об ошибке

**Comment by kamabzalov** [comment]
@JSDID, от тестировщицы:

Все равно у меня не удаляется фотография, что я загружаю. Можно проверить на mobile5 password, права есть на удаление. После перезагрузки страницы, файлы пропадают, при нажатии на крестики ничего не происходит

[Screencast_from_2024-07-22_00-09-11.webm](https://github.com/user-attachments/assets/99ad5988-50f3-4c2a-89a4-f305a40e63a6)

**Comment by JSDID** [comment]
Все там отрабатывает. Я на видео не вижу, что-бы нажималась кнопка Save для того, что-бы сохранялись права

**Comment by JSDID** [comment]
https://icecreamapps.com/v/bkm2vyu

**Comment by JSDID** [comment]
Проверил на mobile5, все загрузки и удаления отрабатывают корректно. Возможно проблема в том, что на видео не видно, что контакт сохранялся (кнопка Save). Права у нас сохраняются только при нажатии общего сохранения контакта, а не сразу при загрузке в поле.

**Comment by JSDID** [comment]
https://icecreamapps.com/v/bkm2vyu

**Comment by JSDID** [comment]
https://icecreamapps.com/v/bkm2vyu

**Comment by JSDID** [comment]
curl "https://app.admss.com/api/v1/accounts/68e4feac-af69-4257-890a-01485e236afc/listactivity" ^  -H "Accept: application/json, text/plain, */*" ^
  -H "Accept-Language: uk-UA,uk;q=0.9,en-US;q=0.8,en;q=0.7" ^  -H "Authorization: Bearer 0472625a-07b1-45a8-abab-b5a8c15be610" ^
  -H "Connection: keep-alive" ^  -H "DNT: 1" ^
  -H "Origin: http://localhost:3003" ^  -H "Referer: http://localhost:3003/" ^
  -H "Sec-Fetch-Dest: empty" ^  -H "Sec-Fetch-Mode: cors" ^
  -H "Sec-Fetch-Site: cross-site" ^  -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" ^
  -H ^"sec-ch-ua: ^\^"Chromium^\^";v=^\^"123^\^", ^\^"Not:A-Brand^\^";v=^\^"8^\^"^" ^  -H "sec-ch-ua-mobile: ?0" ^
  -H ^"sec-ch-ua-platform: ^\^"Windows^\^"^"

**Comment by JSDID** [comment]
![photo_2024-07-23_11-45-32](https://github.com/user-attachments/assets/7d5a29bb-97fc-4d68-a94c-58a5402596fd)
![photo_2024-07-23_11-45-45](https://github.com/user-attachments/assets/1c0e0c5e-b3f2-493d-a44d-73b86a90d4e3)

**Comment by kamabzalov** [comment]
@JSDID апдейт:

Картинку можно добавить, удалить по одной.

Но если добавить картинку и нажать back, а потом вернуться на этот экран - то картинку я не вижу, и кнопки добавить картинки нет. После сохранения - картинка сохраняется.
[Uploading Screencast_from_2024-07-23_21-41-00.webm…]()

**Comment by kamabzalov** [comment]
@JSDID последний штрих:
Отцентровать этот блок
![image](https://github.com/user-attachments/assets/480d9918-f84a-48ff-b11c-ab9cc2dbedf3)

**Comment by kamabzalov** [comment]
@JSDID 
Если сохранить картинки, потом их удалить и сохранить контакт, то после повторного открытия картинки остаются и не удаляются

[Screencast_from_2024-07-25_19-16-06.webm](https://github.com/user-attachments/assets/ec59159f-2205-4d76-a296-14bdfd3cd071)

**Comment by kamabzalov** [comment]
@JSDID 

не соблюдены расстояния у элементов в модальном окне подтверждения удаления

![image](https://github.com/user-attachments/assets/55d2cfc9-af3b-45e1-9b37-3c2783df6050)


Очень много раз не соблюдаете дизайн! Во многих задачах
