### ISSUE TITLE
Сортировка в Export to WEB

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#472]
При сортировки в Export to WEB по цене у нас сортируется таблица в Inventory, а таблица в Export to WEB становится пустой

![image](https://github.com/kamabzalov/admss-client/assets/49127222/c613d717-89f6-44b1-827f-8f9960c36cef)

Шаги:

1. Зайти в Export to WEB
2. Выбрать колонку Price
3. Отсортировать по ней

AR: таблица становится пустой, а вот таблица в Inventory отсортировывается по цене
ER: таблица отсортировывается по цене
Также не отрабатывает сортировка в history, если дважды нажать на айдишку записи

**Comment by JSDID** [comment]
https://icecreamapps.com/v/cypf3ff - этого бага нет.

**Comment by kamabzalov** [comment]
@JSDID этого это какого? Вы про всю задачу?
