### ISSUE TITLE
Кнопки в Export to WEB/Schedule

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#475]
По нажатию на кнопки старта, паузы, удаления ничего не происходит и нет никакого оповещения.

Так же цвет кнопок по нажатию отличается от дизайна

![image](https://github.com/kamabzalov/admss-client/assets/49127222/62857bbb-00d3-4903-9ced-01226de5db16)

**Comment by kamabzalov** [comment]
@JSDID добавить диалог подвтерждения удаления (перед выполнением запроса на удаление)

**Comment by kamabzalov** [comment]
@JSDID 

после нажатия на паузу, статус меняетсЯ, но мы этого не видим, пока не перезагрузим страницу мануально. Также будучи в schedule, если перезагрузить страницу нас перекидывает назад в export to web.

Еще если у нас только 1 запись или нет записей, но весь блок теряет свою высоту, а высота должна быть статична

![image](https://github.com/user-attachments/assets/7ec16328-7aa5-49a9-a19d-32208b231345)

После удаления тоже надо перезагружать страницу, чтобы запись пропала

**Comment by kamabzalov** [comment]
@JSDID Кнопка удаление не того цвета
![image](https://github.com/user-attachments/assets/eed64de0-8ecf-44c8-85d8-46156d950139)

Проверяйте дизайн! Из-за таких мелочей не можем днями закрыть задачи

**Comment by kamabzalov** [comment]
@JSDID 

![image](https://github.com/user-attachments/assets/76d5d2d3-2cf2-4c66-b76d-95de4a7cc873)

Это как можно не заметить????
В следующий раз штраф буду назначать за невнимательность

**Comment by kamabzalov** [comment]
@JSDID, от тестировщицы:

Кеш я сбрасывала. Вот видео с инкогнито, кнопка становится правильного цвета только после нажатия на Cancel или на Delete

[Screencast_from_2024-08-07_22-00-28.webm](https://github.com/user-attachments/assets/0b7c8b50-dd1f-40f3-9346-46bd53ef39b1)

**Comment by kamabzalov** [comment]
@JSDID 
это тоже чините

![image](https://github.com/user-attachments/assets/55a3ade8-9d20-404d-bd9a-8dbeb746bec5)

Еще заказчик говорит - в истории пагинация не работает

**Comment by JSDID** [comment]
https://icecreamapps.com/v/fy8t6g4

это по поводу Пагинации
