### ISSUE TITLE
Export to WEB css fix

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#482]
1. По дизайну стрелки сортировки колонов черного цвета, а не серого.
2. Лищняя пустая колонка в Schedule
![image](https://github.com/kamabzalov/admss-client/assets/49127222/ab60bec3-5b07-4edd-af7d-f54d294cb1c4)
3. При отсутствии записей, нет 1 в пагинации, надо показывать 1 все равно
4. Иконка скачивания таблицы отличается от дизайна
![image](https://github.com/kamabzalov/admss-client/assets/49127222/3d4e4e4f-fdea-458f-9e88-48c1ec9799ea)
5. В истории, хоть и найдены записи, в пагинации нет цифр
![image](https://github.com/kamabzalov/admss-client/assets/49127222/1f9a7397-b613-4124-89d7-c0679a862330)
6. Нет поисковика в history и schedule, по дизайну есть
7. Нет тултипов на кнопках в расписании, в дизайне есть
![image](https://github.com/kamabzalov/admss-client/assets/49127222/bf19709f-965f-4574-87a0-0882c4927fba)

**Comment by kamabzalov** [comment]
@JSDID  в истории есть - [auto dealer](https://www.figma.com/design/BDg0gIw134tMRsEwMUa3G4/auto-dealer?node-id=5232-26842&t=0Rvv5I3bMQLFsxzn-4)

**Comment by kamabzalov** [comment]
@JSDID GET /api/v1/external/{useruid}/listhistory - get item export history
проверьте поиск во вкладке history

**Comment by JSDID** [comment]
Что именно проверить? Запрос уходит от нас.

**Comment by JSDID** [comment]
![photo_2024-07-15_11-03-21](https://github.com/user-attachments/assets/3f9711ff-1fbb-46f8-9a54-fa0e73ab5d84)
![photo_2024-07-15_11-04-20](https://github.com/user-attachments/assets/89f1701e-8b22-4bf7-84ec-3203e099f9ac)
![photo_2024-07-15_11-04-50](https://github.com/user-attachments/assets/f25f5487-4603-4b3b-a071-147f29219140)
бек параметр qry просто игнорирует

**Comment by kamabzalov** [comment]
@JSDID 
Иконки старта, паузы и удаления отличаются от дизайна и стали как-то толще по сравнению с тем, что было.
