### ISSUE TITLE
Убрать хедер в карточке создания контакта

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#499]
В карточке создания в шапке блока с инфой прописывается ФИ, и имя компании - а должно быть только в редактировании

![image](https://github.com/user-attachments/assets/7a1ca3ee-5013-4d3e-bcae-bdf8b334c81d)

**Comment by JSDID** [comment]
![photo_2024-10-24_18-25-11](https://github.com/user-attachments/assets/58b3b836-ebe0-468a-9584-06899e2bac66)
![photo_2024-10-24_18-25-11 (2)](https://github.com/user-attachments/assets/a363f032-b9f6-4c34-97bc-68957923f5b6)

Задача неактуальна. То что описано в задаче уже реализовано на мастере.
