### ISSUE TITLE
Фильтрация инвентории по типу инвентории

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#520]
Если фильтровать инвенторию по типу используя 1 группу, все возращается верно. Но если использовать 2 группы, то такое ощущение, что работает только первая.

Т.е. если по 1 группу ничего не возращается, а по 2ой должны вернуться записи, то мы получим ничего.

**Comment by JSDID** [comment]
От нас данные уходят корректно (согласно инструкциям по которым писались фильтры). То что возвращает сервер - на это я повлиять не могу. Не ошибка фронтенда.

**Comment by JSDID** [comment]
curl 'https://app.admss.com/api/v1/inventory/33e88d0e-fa44-4e1d-a279-e8a72f9bbbbb/list?skip=0&top=20&qry=sold.Status%2Bover90.Age&total=1' \  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: uk-UA,uk;q=0.9,en-US;q=0.8,en;q=0.7' \  -H 'Authorization: Bearer 4de2f7e2-f6a9-49c6-aa38-100969ac683d' \
  -H 'Connection: keep-alive' \  -H 'DNT: 1' \
  -H 'Origin: http://localhost:3003' \  -H 'Referer: http://localhost:3003/' \
  -H 'Sec-Fetch-Dest: empty' \  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="123", "Not:A-Brand";v="8"' \  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"'

**Comment by kamabzalov** [comment]
@JSDID ок, передал на проверку
