### ISSUE TITLE
Чекбокс Export to web в инвентории

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#549]
Если зайти в уже сохраненную инвенторию и открыть Export to WEB → Price and comments и нажать на чекбокс, то кнопка сохранения изменений остается серой, а должна стать зеленой и позволить сохранить изменения

**Comment by JSDID** [comment]
Проблема в том, что изначально этот чекбокс работает локально, и он не имеет влияние на изменение данных (почему и кнопка не изменяла свое состояние, потому что данные не изменялись). Его логика была в том, что он просто позволял/запрещал редактировать остальные поля в export to web. даже сейчас он ничего он в форме не меняет, но просто появилась возможность ее отправить повторно на сервер в том же виде, в котором она была до этого. Возможно есть смысл ее привязать к API.

**Comment by kamabzalov** [comment]
@JSDID как просили

GET /api/v1/inventory/{inventoryuid}/webcheck
POST /api/v1/inventory/{inventoryuid}/webcheck

в пайлоаде

”enabled” : 0 или 1

**Comment by kamabzalov** [comment]
@JSDID 
по умолчанию должен быть включен

**Comment by JSDID** [comment]
Инвентории правда сейчас не читаются. Запрос уходит в вечный pending и потом отрубается по таймауту. 

Cписок инвенторий нормально отвечает, а отдельная инвентория - нет. Позавчера была обратная ситуация. Список не читался, а инвентория отвечала.

![photo_2024-08-23_14-14-04](https://github.com/user-attachments/assets/5d935b44-81f5-46cf-b0a0-7c0d72b1ad89)

**Comment by kamabzalov** [comment]
@JSDID PR подготовьте. Когда заработает, проверите

**Comment by kamabzalov** [comment]
@JSDID Могу ввести 3 цифры после запятой, а должно быть только 2
![image](https://github.com/user-attachments/assets/3d3b58e5-4738-43c3-a978-4b0e84f47f48)
