### ISSUE TITLE
Проблемы в Export to Web

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#552]
1. Добавить возможность редактирование цены прямо в таблице со всеми записями, в колонке Price
![image](https://github.com/user-attachments/assets/fba01ab5-00c2-4ca2-b58a-6b5638f34c64)
2. Не сохраняются колонки сервисов, если до этого их включить и потом перейти
3. Если зайти из листа экспорта в редактировании инвентории, и потом закрыть ее, то мы попадаем в лист инвентории, а должны вернуться в лист экспорта

**Comment by JSDID** [comment]
![IMG_20240821_170251_071.jpg](https://github.com/user-attachments/assets/3dfae0f6-033f-4388-9eee-515d6256cb57)

**Comment by kamabzalov** [comment]
@JSDID ненадо об ошибка на бэке сообщать - это не наша вина. Ждите/мониторьте

**Comment by kamabzalov** [comment]
@JSDID проверяйте апи

**Comment by JSDID** [comment]
![photo_2024-08-24_10-30-39](https://github.com/user-attachments/assets/27281b6a-3f91-403e-8230-79b742670563)

**Comment by kamabzalov** [comment]
@JSDID цену меняем когда фокус уходит или энтер, т.е ввели что-то нажали энтер данные ушли. Ввели другую цену, перешли на другое поле данные тоже ушли.

Сейчас нельзя изменить цену
[Screencast_from_2024-08-29_16-26-12.webm](https://github.com/user-attachments/assets/817dae8e-f8a2-4381-9bfb-cb783552ba48)


Дата последнего экспорта все так же не прописывается, хотя приходит

**Comment by JSDID** [comment]
Изменился ответ от бека. Сейчас много других/измененных полей приходит. Раньше было добавлено поле mediacount, а теперь его снова нет. Соответственно колонка Media (qty) будет пустой. Нужно попросить бека вернуть ее в ответ. Last export не показывался опять же из-за изменений на беке. Раньше поле было в нижнем регистре, а тепер в Capitalize. (это пофикшено)

**Comment by kamabzalov** [comment]
@JSDID бэк пишет
в сваггере всё есть, на бэке, как я вижу, тоже

уточни, плиз


Поэтому я и прошу всегда запросы прикладывать.
Можно и ответы (json)

**Comment by JSDID** [comment]
Я просто сообщил о том, что интерфейс ответа изменился снова, никто ничего не говорил. Я уже переписал все актуально. Просто единственно что media qty нет в запросе снова (до изменений - был), который специально добавляли месяц назад, так как его тоже не было

**Comment by kamabzalov** [comment]
Так я не понял - сейчас все нормально?

**Comment by JSDID** [comment]
Сейчас все нормально. Кроме колонки Media

Раньше было добавлено поле mediacount, а теперь его снова нет. Соответственно колонка Media (qty) будет пустой. Нужно попросить бека вернуть ее в ответ.

**Comment by kamabzalov** [comment]
@JSDID 

1.Пропало сохранение колонок. Если выбрать все колонки на отображение, а потом перейти в Schedule и вернуться назад, то колонки будут показываться в сокращенном виде.

2.А нельзя при наводе фокуса на колонку с ценой, показывать поле так же как в сервисе? Иначе нет ощущения, что поле можно изменять. Просто пропадает значок доллара

![image](https://github.com/user-attachments/assets/ac7ea360-c712-4e7b-a93f-03cb9cf825ee)

**Comment by JSDID** [comment]
Сохранение колонок - работает. Оно может не работать только в случае если сервер не отвечает (не записывает или не читает данные с profile).

**Comment by JSDID** [comment]
https://icecreamapps.com/v/e259pah

**Comment by kamabzalov** [comment]
> Сохранение колонок - работает. Оно может не работать только в случае если сервер не отвечает (не записывает или не читает данные с profile).
> 
> https://icecreamapps.com/v/e259pah

@JSDID 

Select all не выбирает сервисы. Проверить полностью выборку и сохранение

**Comment by kamabzalov** [comment]
@JSDID 

`curl 'https://app.admss.com/api/v1/external/d51ffe3a-10d3-497e-a4d2-61894dae2b2e/schedule?qry=&skip=0&top=20&total=1' \
  -H 'sec-ch-ua: "Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Referer: https://app.admss.com:3002/' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'Authorization: Bearer ffe9e745-480a-432e-a89b-4432c4950efb' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/[127.0.0.0](https://127.0.0.0/) Safari/537.36' \
  -H 'sec-ch-ua-platform: "Linux"'
при переходе в Schedule  в Export to WEb мы отправляем этот запрос`

qry= лишнее

**Comment by kamabzalov** [comment]
@JSDID 
Если выбрать отображать колонки сервисов, а после перейти в Schedule и вернуться назад в Export to WEB, то чекбоксы у названия колонок сначала отмечены как выбранные, а потом эта галочка пропадает. Было бы хорошо сразу отображать их не выбранными, если они не были выбранны

[Screencast_from_2024-09-03_18-48-26.webm](https://github.com/user-attachments/assets/7066ef4c-7ce0-4671-b818-e0bd0ed97706)

**Comment by kamabzalov** [comment]
@JSDID проблема еще актуальна

[Screencast_from_2024-09-04_21-07-22.webm](https://github.com/user-attachments/assets/a2fc05e7-0a93-4bbc-a521-c224115653bd)

**Comment by JSDID** [comment]
У меня ок 

https://icecreamapps.com/v/gs8zhen
