### ISSUE TITLE
Конец сессии

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#564]
После окончания сессии, если попробовать перейти куда-то, то должно разлогинить, а сейчас показывает так

![image](https://github.com/user-attachments/assets/50301ea6-abd2-4cb9-b9eb-6a59d0a3383f)

**Comment by JSDID** [comment]
Таска уже не актуальна. Бек возвращает 401 и нас выкидывает на логин

**Comment by kamabzalov** [comment]
> Таска уже не актуальна. Бек возвращает 401 и нас выкидывает на логин

Ок, отпишу тестировщице и закрою, если все ок
