### ISSUE TITLE
Отображение данных в контакте

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#569]
В контаке у нас приходит информация с номером прав, и вот номер в ответе запроса и на фронте отличается. Как мы видим в поле

Driver license’s number - 6346346346346346

в то время в запросе "dl_number" : "000039254344",

![image](https://github.com/user-attachments/assets/7c02422e-2dc5-4d60-8b73-05e3f2c25f6f)

**Comment by JSDID** [comment]
Потому что это другое поле. Правильное поле, к которому мы привязаны (а поля мы привязываем те, что говорит бек) - extdata.Buyer_Driver_License_Num

**Comment by kamabzalov** [comment]
@JSDID ok, уточню

**Comment by JSDID** [comment]
https://github.com/kamabzalov/admss-client/pull/122#issuecomment-1950240361 нашел
![IMG_20240830_142913_007.jpg](https://github.com/user-attachments/assets/4b57461a-4c4b-49c8-9564-6ca08b4b41a0)

**Comment by kamabzalov** [comment]
@JSDID ответ от бэка:

если это просто контакт - dl_number
а вот если он как покупатель - Buyer_Driver_License_Num

**Comment by JSDID** [comment]
Это как понимать? Что нужно сделать?

**Comment by JSDID** [comment]
Это как понимать? Что нужно сделать? 

Как мне это определять? С помощью карт?

У нас есть тип контакта

![IMG_20240902_141000_357.jpg](https://github.com/user-attachments/assets/fe4dc451-ca4f-4776-8e4d-0873fcea281a)

Но тут много типов

для Buyers dl_number а для остальных Buyer_Driver_License_Num?

**Comment by kamabzalov** [comment]
@JSDID 
Для buyer - Buyer_Driver_License_Num, если оно пустое - берём из dl_number

Для остальных - dl_number
