### ISSUE TITLE
F&I PRODUCTS in deals

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#570]
В F&I PRODUCTS сразу есть дроп Duration, по дизайну он появляется только после заполнения Term, если там выбрать месяцы

**Comment by JSDID** [comment]
Эта логика уже делалась, непонятно почему почему опять таска вылезла, если это уже давно работает

![IMG_20240830_145326_408.jpg](https://github.com/user-attachments/assets/877d66c3-f577-4dbd-ad1b-09c1fcc0f3bf)

![IMG_20240830_145326_551.jpg](https://github.com/user-attachments/assets/aae090c4-bcae-4f51-b86b-5dfd565fbb44)

**Comment by kamabzalov** [comment]
@JSDID хорошо, запрошу еще раз проверить

**Comment by JSDID** [comment]
Это уже делалось, и в данный момент имено так и  отрабатывает на мастере

![IMG_20240830_145326_551.jpg](https://github.com/user-attachments/assets/aae090c4-bcae-4f51-b86b-5dfd565fbb44)
