### ISSUE TITLE
Создание аккаунта по сделке

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#576]
При отображении сделок, мы в колонке Account отображаем accountuid, а должны accountInfo.

При создании сделки, если мы заполнили поле Account number мы его отправляем как accountuid, а должны как accountInfo

**Comment by JSDID** [comment]
![photo_2024-09-07_16-26-24](https://github.com/user-attachments/assets/efd0dd9d-a0c1-4558-b0b6-ca28e5d16672)


curl 'https://app.admss.com/api/v1/accounts/9656a62d-c7c1-477f-8261-d7fc83be2e72/paymentinfo' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6' \
  -H 'Authorization: Bearer d8cd0f31-5304-4f7c-8457-139e371d7891' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:3003' \
  -H 'Referer: http://localhost:3003/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"'

**Comment by JSDID** [comment]
По этому curl  - нет нужных данных для вкладки Quick pay (check$, fees, change, payment notes и другие показанные на скриншоте)

**Comment by JSDID** [comment]
Нам нужно вывести что-то в дроп, а опций никаких нет. Возможно такое, что их там и не будет в каких-то случаях, но что в таком случае тогда делать с dropdown? Делать его disabled?

![photo_2024-09-07_16-23-52](https://github.com/user-attachments/assets/77b6f0ed-6778-44c0-bba5-4a94afd9a4b8)

**Comment by JSDID** [comment]
![photo_2024-09-07_16-23-52](https://github.com/user-attachments/assets/ad864c34-6062-444a-8fee-d8ebad8fea4e)

![photo_2024-09-07_15-49-45](https://github.com/user-attachments/assets/c18eb567-dd2c-4b5a-927d-8152851ebe36)


Как нам из одного объекта получить список пользователей и их доступами? Я уже спрашивал об этом несколько раз. Опять говорят что готово, а по итогу ответ такой же как и был. Может я не понимаю? Нужно объяснение, как мне с этого ответа сделать то, что нарисовано в дизайне?

**Comment by JSDID** [comment]
По коду видно что поменяно

![photo_2024-09-09_13-54-24](https://github.com/user-attachments/assets/0ace5e82-93da-4979-8448-3304a09084d5)
