### ISSUE TITLE
Support history

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#579]
При нажатии на See more у нас открывается страница Not found

хотя апи вернуло 200

[Screencast_from_2024-09-03_19-11-08.webm](https://github.com/user-attachments/assets/8ed4966d-4e99-442d-bd8b-b8164038dfdf)

**Comment by JSDID** [comment]
У меня ок https://icecreamapps.com/v/c6k39eq

**Comment by kamabzalov** [comment]
@JSDID попрошу проверить актуальность тестировщицу

**Comment by kamabzalov** [comment]
@JSDID посмотрите пока в др браузерах (инкогнито/кэш)

**Comment by kamabzalov** [comment]
@JSDID проверьте на mobile2
[Uploading Screencast_from_2024-09-05_17-35-05.webm…]()

**Comment by JSDID** [comment]
https://icecreamapps.com/v/ebt5xqd - ошибки нет
