### ISSUE TITLE
Добавление API в разделе Take Payment (Quick pay tab)

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#583]

**Comment by JSDID** [comment]
![photo_2024-09-06_11-52-12 (2)](https://github.com/user-attachments/assets/dff4e820-1dbb-4473-9cf5-d38f53cd13c3)
![photo_2024-09-06_11-52-12](https://github.com/user-attachments/assets/39d32c80-3b1e-4233-918b-9f43823b4d3c)
![photo_2024-09-06_11-21-05](https://github.com/user-attachments/assets/fc206e6e-6544-4b28-911e-745edd15e53d)
]
Не работает ендпоинт /api/v1/accounts/{useruid}/drawers

curl 'https://app.admss.com/api/v1/accounts/33e88d0e-fa44-4e1d-a279-e8a72f9bbbbb/drawers' \  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: uk-UA,uk;q=0.9,en-US;q=0.8,en;q=0.7' \  -H 'Authorization: Bearer 4de2f7e2-f6a9-49c6-aa38-100969ac683d' \
  -H 'Connection: keep-alive' \  -H 'DNT: 1' \
  -H 'Origin: http://localhost:3003' \  -H 'Referer: http://localhost:3003/' \
  -H 'Sec-Fetch-Dest: empty' \  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="123", "Not:A-Brand";v="8"' \  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"'

**Comment by JSDID** [comment]
![photo_2024-09-06_11-21-05](https://github.com/user-attachments/assets/fc206e6e-6544-4b28-911e-745edd15e53d)

**Comment by kamabzalov** [comment]
@JSDID отправил. Ждем ответа

**Comment by JSDID** [comment]
Не нашел этих полей в ответе GET /api/v1/accounts/{accountuid}/paymentinfo

![photo_2024-09-06_16-39-32](https://github.com/user-attachments/assets/912a1e6e-19fc-44f8-a20b-2121b82d240e)

**Comment by JSDID** [comment]
Это когда мы например по этой кнопке (и там еще несколько) щелкаем

![IMG_20240906_170253_300.jpg](https://github.com/user-attachments/assets/a013e90e-4082-4081-9d04-94f23ccbec82)

**Comment by kamabzalov** [comment]
> Какое поле отвечает за Total Payoff?
> 
> ![photo_2024-09-06_11-21-05](https://private-user-images.githubusercontent.com/102165823/365142061-fc206e6e-6544-4b28-911e-745edd15e53d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NDEzNDQsIm5iZiI6MTcyNTY0MTA0NCwicGF0aCI6Ii8xMDIxNjU4MjMvMzY1MTQyMDYxLWZjMjA2ZTZlLTY1NDQtNGIyOC05MTFlLTc0NWVkZDE1ZTUzZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxNjQ0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTExMDAyMWE2YTQ3NmQyNzRiYmQ5ZGM0N2U5OTE5ZDkxNDRmNTE5MjlmYzQ1ZDk1OTUzNTRiZWNmZWZmYzljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dlguB7oGkOXrTyvcVGNFs1pexIamW2oQTUiEbVN66_c)

@JSDID TotalPaid

**Comment by kamabzalov** [comment]
> ![photo_2024-09-06_11-52-12 (2)](https://private-user-images.githubusercontent.com/102165823/365142056-dff4e820-1dbb-4473-9cf5-d38f53cd13c3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NDEzNDQsIm5iZiI6MTcyNTY0MTA0NCwicGF0aCI6Ii8xMDIxNjU4MjMvMzY1MTQyMDU2LWRmZjRlODIwLTFkYmItNDQ3My05Y2Y1LWQzOGY1M2NkMTNjMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxNjQ0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDU0YWZmODA2N2Y5ZGRjODI2Y2QyMmJjNzk5OWExMjlkYTliNWMxMzM2OGJjZmQxMDM0YzhjMDJiZmY5YWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KxLy2stbgTXweeLfF_qpI6D-xrwFl-u6q9E-wm51xX8) ![photo_2024-09-06_11-52-12](https://private-user-images.githubusercontent.com/102165823/365142058-39d32c80-3b1e-4233-918b-9f43823b4d3c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NDEzNDQsIm5iZiI6MTcyNTY0MTA0NCwicGF0aCI6Ii8xMDIxNjU4MjMvMzY1MTQyMDU4LTM5ZDMyYzgwLTNiMWUtNDIzMy05MThiLTlmNDM4MjNiNGQzYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxNjQ0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzMxNzMwNzgwYWE3ZmJhZTQwMzk5ODZhYjA5MDJmOWNlNTMxZDJlNjc3ODE4Y2Q1MDhhY2I1M2EwMTYwNjQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KR9z51VKtCEIkLJQ5gV5TDKuDFEDymTgK4r-DJi2p54)
> 
> Не работает ендпоинт /api/v1/accounts/{useruid}/drawers
> 
> curl 'https://app.admss.com/api/v1/accounts/33e88d0e-fa44-4e1d-a279-e8a72f9bbbbb/drawers' \ -H 'Accept: application/json, text/plain, _/_' -H 'Accept-Language: uk-UA,uk;q=0.9,en-US;q=0.8,en;q=0.7' \ -H 'Authorization: Bearer 4de2f7e2-f6a9-49c6-aa38-100969ac683d' -H 'Connection: keep-alive' \ -H 'DNT: 1' -H 'Origin: http://localhost:3003' \ -H 'Referer: http://localhost:3003/' -H 'Sec-Fetch-Dest: empty' \ -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: cross-site' \ -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' -H 'sec-ch-ua: "Chromium";v="123", "Not:A-Brand";v="8"' \ -H 'sec-ch-ua-mobile: ?0' -H 'sec-ch-ua-platform: "Windows"'

бэк пишет что исправлено

**Comment by kamabzalov** [comment]
@JSDID 

также drawers по прежнему пустой.

Надо внести туда что-то заранее
POST /api/v1/accounts/{useruid}/drawer

**Comment by kamabzalov** [comment]
> Не нашел этих полей в ответе GET /api/v1/accounts/{accountuid}/paymentinfo
> 
> ![photo_2024-09-06_16-39-32](https://private-user-images.githubusercontent.com/102165823/365188412-912a1e6e-19fc-44f8-a20b-2121b82d240e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MjU3ODMsIm5iZiI6MTcyNTcyNTQ4MywicGF0aCI6Ii8xMDIxNjU4MjMvMzY1MTg4NDEyLTkxMmExZTZlLTE5ZmMtNDRmOC1hMjBiLTIxMjFiODJkMjQwZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QxNjExMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTk0MWNmMWI3ZWY2NTIxMjM5ODI4ZjgzODkwYWEzYWY0ZWYwODcxZWUwMDNhOGM0MTViZjhkMjcxZDRhYTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.94DTNALYcdhPNuQQr7K17IXsMAjN4i9VeNZl4XBSipI)

@JSDID эти данные вносятся пользователем

**Comment by JSDID** [comment]
![photo_2024-09-07_16-26-24](https://github.com/user-attachments/assets/74a4e46c-3887-4fbe-a663-69eae9c523b3)

По этому curl  - нет нужных данных для вкладки Quick pay (check$, fees, change, payment notes и другие показаные на скриншоте)

curl 'https://app.admss.com/api/v1/accounts/9656a62d-c7c1-477f-8261-d7fc83be2e72/paymentinfo' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6' \
  -H 'Authorization: Bearer d8cd0f31-5304-4f7c-8457-139e371d7891' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:3003' \
  -H 'Referer: http://localhost:3003/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"'

**Comment by JSDID** [comment]
Нам нужно вывести что-то в дроп, а опций никаких нет. Возможно такое, что их там и не будет в каких-то случаях, но что в таком случае тогда делать с dropdown? Делать его disabled?

![photo_2024-09-07_16-23-52](https://github.com/user-attachments/assets/5914a5b1-7ef0-45e8-9c23-b78112ebcb4a)

**Comment by JSDID** [comment]
![photo_2024-09-07_15-49-45](https://github.com/user-attachments/assets/2efdac8b-d816-43b3-9375-bc85c78fbb39)

Как нам из одного объекта получить список пользователей и их доступами? Я уже спрашивал об этом несколько раз. Опять говорят что готово, а по итогу ответ такой же как и был. Может я не понимаю? Нужно объяснение, как мне с этого ответа сделать то, что нарисовано в дизайне?

![photo_2024-09-07_15-46-31](https://github.com/user-attachments/assets/d3b84f51-1609-4bbf-bf86-58a166db159f)

**Comment by JSDID** [comment]
![photo_2024-09-07_15-46-31](https://github.com/user-attachments/assets/54913958-c9cb-45c2-ab86-6b9621fdc0c8)

Как нам из одного объекта получить список пользователей и их доступами? Я уже спрашивал об этом несколько раз. Опять говорят что готово, а по итогу ответ такой же как и был. Может я не понимаю? Нужно объяснение, как мне с этого ответа сделать то, что нарисовано в дизайне?

![photo_2024-09-07_15-49-45](https://github.com/user-attachments/assets/e8508de7-c7c7-4a9a-89dc-0e393e3f1c22)

**Comment by JSDID** [comment]
У нас есть место, откуда мы можем это внести? Или через postman вносить?

![photo_2024-09-08_12-18-49](https://github.com/user-attachments/assets/558e8342-8e57-4e56-adad-3482a36e3e6f)

**Comment by kamabzalov** [comment]
> У нас есть место, откуда мы можем это внести? Или через postman вносить?
> 
> ![photo_2024-09-08_12-18-49](https://private-user-images.githubusercontent.com/102165823/365429975-558e8342-8e57-4e56-adad-3482a36e3e6f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3OTExODIsIm5iZiI6MTcyNTc5MDg4MiwicGF0aCI6Ii8xMDIxNjU4MjMvMzY1NDI5OTc1LTU1OGU4MzQyLThlNTctNGU1Ni1hZGFkLTM0ODJhMzZlM2U2Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxMDIxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTY1MDhmZGJiNTNhYTk4NmE0ODFjZDllOWIxMzc2OTE0NTMzNDIyODgwYTQ4OWFjM2ExOTQ4ZWNlOGFmMzc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VR38vb3whePMpkXfJ2btRUrN-Ow73y6HEnUBLbbMUc8)

@JSDID метод есть. Вносить через postman. Забудьте о моках со стороны бэка

**Comment by JSDID** [comment]
Вот я отправляю то, что у меня есть (itemuid пустой или 0, так как itemuid логично что пока не создан - его нет)

![photo_2024-09-08_12-18-49](https://github.com/user-attachments/assets/43b877a9-7016-4d7c-9480-cb08df58b80f)
![photo_2024-09-08_15-30-33](https://github.com/user-attachments/assets/78e2c4da-554c-4824-8f00-0fbf27f7f0fc)

**Comment by kamabzalov** [comment]
@JSDID вот теперь стало понятнее. Отправлю бэку

**Comment by JSDID** [comment]
curl --location 'https://app.admss.com/api/v1/accounts/68e4feac-af69-4257-890a-01485e236afc/drawer' \ 
--header 'Content-Type: application/json' \ 
--header 'Accept: application/json' \ 
--header 'Authorization: ••••••' \ 
--data '{ 
  "useruid": 33e88d0e-fa44-4e1d-a279-e8a72f9bbbbb, 
  "drawer": "test" 
}'

**Comment by JSDID** [comment]
Он их обрезанными генерирует (ну понятно, что браузер тут не описан) но все равно выглядит не полным

**Comment by JSDID** [comment]
curl --location 'https://app.admss.com/api/v1/accounts/68e4feac-af69-4257-890a-01485e236afc/drawer' \--header 'Content-Type: application/json' \
--header 'Accept: application/json' \--header 'Authorization: Bearer 0ad808a3-3160-4438-b8ce-c7848d06f5ac' \
--data '{  "itemuid": "0",
  "useruid": 33e88d0e-fa44-4e1d-a279-e8a72f9bbbbb,  "drawer": "test"
}'

**Comment by kamabzalov** [comment]
@JSDID 
бэк пишет:

Drawers привязаны не к аккаунту, а к юзеру.

При создании вызываем
POST /api/v1/accounts/{itemuid}/drawer
itemuid - это UID записи а не аккаунта

тоесть для создания новой записи для юзера надо отправлять
POST /api/v1/accounts/0/drawer

для изменения существующей
POST /api/v1/accounts/{uid_записи}/drawer

**Comment by JSDID** [comment]
![photo_2024-09-08_18-19-37](https://github.com/user-attachments/assets/185c71f9-7f96-44ee-82d0-2adef9da296b)

Создался, но get возвращает такой drawer

[
 {
  "created" : "09/08/2024 15:17:45",
  "drawer" : "",
  "id" : 1,
  "itemuid" : "b4e0be93-991b-4eb3-b679-beb011c85128",
  "useruid" : "33e88d0e-fa44-4e1d-a279-e8a72f9bbbbb"
 }
], 

Поле drawer пустое, хотя я и передал туда имя


curl --location 'https://app.admss.com/api/v1/accounts/0/drawer' \--header 'Content-Type: application/json' \
--header 'Accept: application/json' \--header 'Authorization: Bearer e300e65d-f95d-41f1-bded-3fbb9583b599' \
--data '{  "useruid": 33e88d0e-fa44-4e1d-a279-e8a72f9bbbbb,
  "drawer": "test"}'


![photo_2024-09-08_18-19-58](https://github.com/user-attachments/assets/b42aa38c-f72b-4eb6-98e8-91f5a28947f4)

**Comment by kamabzalov** [comment]
@JSDID принято. Отправил

**Comment by kamabzalov** [comment]
@JSDID был апдейт. Проверьте

**Comment by JSDID** [comment]
С drawers все так же. Вот только что создал, передал имя drawer-1, но мне вернулся drawer: ""

![IMG_20240910_161204_315.jpg](https://github.com/user-attachments/assets/d175ffc9-038f-4b6b-b27f-65845b65288a)

![IMG_20240910_161256_651.jpg](https://github.com/user-attachments/assets/811817db-5520-4e07-b4e6-e702c15467c2)

**Comment by kamabzalov** [comment]
@JSDID верно понял, что проблема с GET методом? Он ничего не отдает?

**Comment by JSDID** [comment]
> @JSDID верно понял, что проблема с GET методом? Он ничего не отдает?

да

**Comment by JSDID** [comment]
> @JSDID верно понял, что проблема с GET методом? Он ничего не отдает?

отдает. Просто POST метод игнорирует поле drawer, которое мы ему передаем

**Comment by kamabzalov** [comment]
@JSDID отправил. Ждем

**Comment by kamabzalov** [comment]
@JSDID бэк пишет

судя по логам 
drawers post принимает пустое значение "drawer" ( о чём он  и пишет в ответе)

проверь, плиз
"drawer" точно латинскими буквами написано? - у меня подобное уже было

**Comment by JSDID** [comment]
да 

![photo_2024-09-10_23-13-20](https://github.com/user-attachments/assets/dcd5a65d-62bc-4782-829b-b28f25fa9d25)

**Comment by JSDID** [comment]
POST drawers: в swagger ничего не изменилось, но если вчера и позавчера можно было отправить поля, и получить пустое поле drawer, то теперь в postman ошибка (перепроверил, все буквы - лат. )

![photo_2024-09-11_16-01-21](https://github.com/user-attachments/assets/03b1b724-c669-412f-91bf-9c25f4d86734)

![photo_2024-09-11_16-01-21 (2)](https://github.com/user-attachments/assets/c2f74ae9-9a77-40d1-a482-22c4e35dfb75)



curl --location 'https://app.admss.com/api/v1/accounts/0/drawer' \--header 'Content-Type: application/json' \
--header 'Accept: application/json' \--header 'Authorization: Bearer 20a0994e-44f8-4252-b8a6-d5c1d8e2a8dd' \
--data '{  "useruid": 33e88d0e-fa44-4e1d-a279-e8a72f9bbbbb,
  "drawer": "drw"}'

**Comment by JSDID** [comment]
![photo_2024-09-12_17-45-59](https://github.com/user-attachments/assets/ba12b5ad-d4f7-4e40-b9af-b3733744e8cd)

drawers - тоже самое, что и вчера. При создании ошибка.

curl --location 'https://app.admss.com/api/v1/accounts/0/drawer' \--header 'Content-Type: application/json' \
--header 'Accept: application/json' \--header 'Authorization: Bearer ced1d0e2-b7bd-4080-925c-a80ee858eac4' \
--data '{  "useruid": 33e88d0e-fa44-4e1d-a279-e8a72f9bbbbb,
  "drawer": "drw12_09"}'

**Comment by JSDID** [comment]
> @JSDID 
> попробуйте в пайлоаде только “drawer“ передавать, без useruid


Но как тогда понять для кого это drawer, если мы в самом пути тоже без id (0) передаём?

**Comment by kamabzalov** [comment]
@JSDID уточню
