### ISSUE TITLE
Декодирование

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#587]
1. При декодировании нет никакого оповещения, как оно прошло. Хотя мы получаем ошибки
![image](https://github.com/user-attachments/assets/aaa28b85-6d14-4fa6-a9f0-0eb2db97a52a)

2. Если при декодировании приходит TypeOfFuel: "Gasoline" то поле типа топлива не заполняется

**Comment by JSDID** [comment]
Обработка ошибок и уведомления добавлены. Но вот с gasoline - проблема. Дело в том (мы уже это неоднократно раньше обсуждали) что вернулись опять id=0, хотя просили бека не возвращать 0 в качестве id, так как prime dropdown его динамически приводит к false, потому поле не заполняется. А GAS(gasoline) как раз и имеет этот id. Потому если есть возможность снова (как было раньше) убрать 0 с id - то хорошо. Если нет - нужно костылить PrimeDropdown (перебирать компонент) для таких случаев. Делать что-то типа не 0, а "0".

**Comment by kamabzalov** [comment]
@JSDID отправил замечание ваше

**Comment by kamabzalov** [comment]
@JSDID 
Уведомления появились, а вот данные заполняются не все
![image](https://github.com/user-attachments/assets/11c270c9-276f-4c30-af23-dda373e26b97)

**Comment by JSDID** [comment]
![photo_2024-09-11_09-13-54](https://github.com/user-attachments/assets/1474a0a2-be05-41cf-bb5d-5691f8fcbf0f)
![photo_2024-09-11_09-13-54 (2)](https://github.com/user-attachments/assets/87a45544-d834-45a4-b936-ea51d7e9ac8c)

Можно ли попросить бека добавить в ответ api/v1/inventory/{id}/info Transmission_id, TypeOfFuel_id и для прочих значений, как это сделано в vindecode? А то у нас сейчас опять проблема, что в inventory мы читаем название, а с decode нам нужно читать id

**Comment by kamabzalov** [comment]
@JSDID 
Если декодировать testtesttesttest то поля не заполняются.

Если открыть просто пустую запись, то дропы в descriptions не имеют названия в дропах, как будто они заплнены пустотой
![image](https://github.com/user-attachments/assets/2eba8bdc-2028-46bf-8102-4c01959fed04)

2GCEK19B051102811 тоже не заполняется все поля, что возвращает

**Comment by kamabzalov** [comment]
> @JSDID Если декодировать testtesttesttest то поля не заполняются.
> 
> Если открыть просто пустую запись, то дропы в descriptions не имеют названия в дропах, как будто они заплнены пустотой ![image](https://private-user-images.githubusercontent.com/49127222/366588039-2eba8bdc-2028-46bf-8102-4c01959fed04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTg1NjMsIm5iZiI6MTcyNjIxODI2MywicGF0aCI6Ii80OTEyNzIyMi8zNjY1ODgwMzktMmViYThiZGMtMjAyOC00NmJmLTgxMDItNGMwMTk1OWZlZDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA5MDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MGJlZmY3NjI3Mjk3NzEzODNjMjYzODJlMWJkMGE4YTRjZGQ3NzFmMmFlNjNkMTBiYjVkMjhkYjMwZWFkZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4d-Dgz9K-4n6NbduTwKmWldHmhxoewjCTS5WHYyy9D8)
> 
> 2GCEK19B051102811 тоже не заполняется все поля, что возвращает

**Comment by kamabzalov** [comment]
@JSDID 
Поле типа топлива заполняется, но если стоит GAS, то пишет, что поле пустое

[Uploading Screencast_from_2024-09-17_02-08-21.webm…]()
