### ISSUE TITLE
Recent messages

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#589]
В recent messages надо убрать хардкорные записи и прицепить апи

[/api/v1/log/{itemuid}/suport](https://app.swaggerhub.com/apis/ADMSS/admss-web_api/0.1.13#/Log/get_api_v1_log__itemuid__suport)

по которому мы там должны отображаться последние сообщения

Также надо доработать отображение сообщений в модальном окне Support history

**Comment by kamabzalov** [comment]
@JSDID 
Когда нет записей, на главном экране не должно быть кнопки See more и текст должен быть не зеленого цвета.

**Comment by JSDID** [comment]
Где это можно увидеть? В дизайне просто нет такого.

**Comment by kamabzalov** [comment]
@JSDID 
![image](https://github.com/user-attachments/assets/5ab46d83-e09a-4a12-9d03-3eb35cbd3fc9)

**Comment by JSDID** [comment]
https://www.figma.com/design/BDg0gIw134tMRsEwMUa3G4/auto-dealer?node-id=3235-1134&node-type=canvas&t=jitmMM53obZnwEwB-0

**Comment by JSDID** [comment]
![photo_2024-09-11_09-43-11](https://github.com/user-attachments/assets/9eba1d83-4083-405b-8244-4be9baad59ba)
![photo_2024-09-11_09-43-11 (2)](https://github.com/user-attachments/assets/686f4649-0656-4e06-85d1-9b6336379747)

тут есть вариант только с записями. Первая запись - зеленого цвета, последующая - нет (я так и сделал). А какое тогда быть должно поведение без записей? Саму таблицу оставить, а See more убрать?

**Comment by kamabzalov** [comment]
@JSDID понял вопрос. Уточню

**Comment by kamabzalov** [comment]
@JSDID ответ от тестировщицы:
![image](https://github.com/user-attachments/assets/4ed1674c-53ce-4686-ab50-72998ae8a5e8)

Но есть вариант модалки, без записей) там надпись черного цвета. Так что зеленым мы подсвечиваем только 1ую запись, если такая есть.

Если записей нет, надо убрать кнопку See more. Таблица остается и надпись No messages found

**Comment by kamabzalov** [comment]
@JSDID 
Если открыть окно с сообщениями и открыть какое-то сообщение, то по второму клику сообщение не закрывается
[Screencast_from_2024-09-12_19-11-05.webm](https://github.com/user-attachments/assets/191c10e5-8dc4-46fc-8c55-517b5dd3bcaf)
