### ISSUE TITLE
Проблема доступа

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#591]
Если попытаться открыть запись (контакт/инвентория и т.д), которая не принадлежит пользователю на котором мы находится, запрос на инфо возвращает 403. Но на фронте у нас открывается пустая запись.

Надо бы сделать так, что если мы получили 403, то мы не откроем вообще запись никакую и на создание тоже.

![image](https://github.com/user-attachments/assets/bddf34b6-2698-4b52-95ec-6551494b75a1)

**Comment by kamabzalov** [comment]
@JSDID 
Пустая страница создания инвентории все равно открывается, надо это убрать
[Screencast_from_2024-09-11_21-29-21.webm](https://github.com/user-attachments/assets/268b059e-c7a9-457f-bcc2-c6cb73be83ec)

**Comment by JSDID** [comment]
Она в любом случае будет открываться, мы переходим по ссылке сразу в компонент, в котором уже идет запрос к серверу, и вот пока мы не получим ответ от сервера, что у нас нет доступа - мы будем на странице (меньше секунды), после чего уже будет редирект.

**Comment by kamabzalov** [comment]
> Она в любом случае будет открываться, мы переходим по ссылке сразу в компонент, в котором уже идет запрос к серверу, и вот пока мы не получим ответ от сервера, что у нас нет доступа - мы будем на странице (меньше секунды), после чего уже будет редирект.

@JSDID надо сделать защищенным или делать навигацю программно. Или loader показывать.
Неаккуратно же смотрится
