### ISSUE TITLE
API для кнопок на странице отчета

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#599]
![image](https://github.com/user-attachments/assets/9c064ee1-d9eb-4e34-824b-7a33d395a7a2)

Реализовать апи для трех кнопок (на скрине): доступ, копирование, удаление

**Comment by JSDID** [comment]
![photo_2024-09-12_21-29-38](https://github.com/user-attachments/assets/5f570dc5-72be-4edc-8342-ad409a3249ca)

Первая - понятно. Это та же самая модалка с доступами. Третья - удаление, в swagger я нашел метод для нее. А вот вторая - duplicate - как быть с ней? Через какой endpoint мы работаем через нее?

**Comment by kamabzalov** [comment]
@JSDID отправил вопрос

**Comment by kamabzalov** [comment]
@JSDID 
POST /api/v1/reports/{templateuid}/copy
