### ISSUE TITLE
Добавление API в разделе Take Payment (Balance Adjustment)

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#606]

**Comment by JSDID** [comment]
Вопрос к беку: куда отправлять данные по этим кнопкам?
![photo_2024-09-15_20-51-29 (2)](https://github.com/user-attachments/assets/fb5e0e4d-1124-495a-861a-4a0516c8a07d)
![photo_2024-09-15_20-51-29](https://github.com/user-attachments/assets/06c7034f-a31e-4c68-8636-5986175181a6)

**Comment by kamabzalov** [comment]
@JSDID отправил вопрос

**Comment by kamabzalov** [comment]
@JSDID 
Apply payment → POST /api/v1/accounts/{accountuid}/takepayment

Стрелочка после amount paid → POST /api/v1/accounts/{accountuid}/checkpayment

**Comment by JSDID** [comment]
Не нашел поля в ответе от сервера

![photo_2024-09-16_09-49-00](https://github.com/user-attachments/assets/41010182-dc3e-45b2-8aaf-9aabd302112b)

**Comment by JSDID** [comment]
Мы тут options тоже читаем из drawers?

![photo_2024-09-16_09-49-31](https://github.com/user-attachments/assets/2a34d3cd-79cb-4e54-bb79-1849e1ec24a2)
