### ISSUE TITLE
Репорты. Доработки

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#620]
Баги

1. Удаление
2. Кнопки-иокнки внутри коллекций
3. Переименовать Custom collections в Custom reports
4. На странице создания отчета hover добавить

Пройтись самому и найти другие неработающие или непонятные моменты и спрашивать здесь

**Comment by JSDID** [comment]
Как удалить коллекцию? Единственный логически подходящий эндпоинт - /api/v1/reports/{collectionuid}/{documentuid}/delete, но ему нужно два id. В коллекции же у нас нету таких id. Допустим что collectionuid = itemUID, но откуда взять documentuid?

**Comment by JSDID** [comment]
![image_2024-09-19_07-49-03](https://github.com/user-attachments/assets/2e8eede2-cc6d-44f7-8f58-ccfd6a2aca22)

**Comment by JSDID** [comment]
Custom Reports у нас сейчас - это моки. У нас нет ендпоинтов для получения Custom Collections/Reports, соответственно действий мы никаких проводить над моками не можем (редактирование/удаление)

isFavorite  - так и не работает, при отправке сервер отвечает что ок, но значение не изменяется, и список favorites остается пустым curl 'https://app.admss.com/api/v1/reports/d0e65e03-8105-4108-8ef0-000000000001/reportinfo' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6' \
  -H 'Authorization: Bearer 4d17517b-b9de-49ed-acca-7eb27e511226' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://localhost:3003' \
  -H 'Referer: http://localhost:3003/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  --data-raw '{"AskForStartAndEndDates":0,"ShowAverages":0,"ShowLineCount":0,"ShowTotals":0,"count":1,"created":"09/18/2024 20:44:06","documentUID":"d0e65e03-8105-4108-8ef0-000000000001","index":0,"isfavorite":1,"itemUID":"a1f6ce22-2da1-4c9a-ad38-65c1d131d8f4","name":"Base inventory report 1","updated":"09/18/2024 20:44:06"}'

**Comment by JSDID** [comment]
![photo_2024-09-19_07-52-46](https://github.com/user-attachments/assets/c4e3492e-dc09-42b2-b231-65f6a6f2788a)

**Comment by JSDID** [comment]
isFavorite - так и не работает, при отправке сервер отвечает что ок, но значение не изменяется, и список favorites остается пустым curl 'https://app.admss.com/api/v1/reports/d0e65e03-8105-4108-8ef0-000000000001/reportinfo'
-H 'Accept: application/json, text/plain, /'
-H 'Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6'
-H 'Authorization: Bearer 4d17517b-b9de-49ed-acca-7eb27e511226'
-H 'Connection: keep-alive'
-H 'Content-Type: application/json'
-H 'Origin: http://localhost:3003/'
-H 'Referer: http://localhost:3003/'
-H 'Sec-Fetch-Dest: empty'
-H 'Sec-Fetch-Mode: cors'
-H 'Sec-Fetch-Site: cross-site'
-H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36'
-H 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"'
-H 'sec-ch-ua-mobile: ?0'
-H 'sec-ch-ua-platform: "Windows"'
--data-raw '{"AskForStartAndEndDates":0,"ShowAverages":0,"ShowLineCount":0,"ShowTotals":0,"count":1,"created":"09/18/2024 20:44:06","documentUID":"d0e65e03-8105-4108-8ef0-000000000001","index":0,"isfavorite":1,"itemUID":"a1f6ce22-2da1-4c9a-ad38-65c1d131d8f4","name":"Base inventory report 1","updated":"09/18/2024 20:44:06"}'

**Comment by kamabzalov** [comment]
@JSDID 
все есть
![image](https://github.com/user-attachments/assets/4579ba70-10ab-41d4-8bf0-c4f0ade1911f)

И почему удаление доступно не для всех? Почему кнопка Delete только в Custom?

**Comment by JSDID** [comment]
curl 'https://app.admss.com/api/v1/reports/158fa85e-b4c0-4c31-bb0d-7164115f5e7e/0/delete' \
-X 'POST' \
-H 'Accept: application/json, text/plain, */*' \
-H 'Authorization: Bearer 2a1b88ac-67fe-451d-9ed6-475f88029834' \
-H 'Sec-Fetch-Site: cross-site' \
-H 'Accept-Language: en-US,en;q=0.9' \
-H 'Accept-Encoding: gzip, deflate, br' \
-H 'Sec-Fetch-Mode: cors' \
-H 'Host: app.admss.com' \
-H 'Origin: http://localhost:3003' \
-H 'Content-Length: 0' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15' \
-H 'Referer: http://localhost:3003/' \
-H 'Connection: keep-alive' \
-H 'Sec-Fetch-Dest: empty'

![photo_2024-09-19_17-18-09](https://github.com/user-attachments/assets/38f99d8e-99e0-4d0d-9aa6-30ae3beb2028)

**Comment by kamabzalov** [comment]
@JSDID 
Add to collection - /api/v1/reports/{collectionuid}/{itemuid}/move

**Comment by JSDID** [comment]
curl 'https://app.admss.com/api/v1/reports/1bcbc10c-4197-4e25-9987-000000000001/1868b9b5-21f5-45cd-b27d-46b808d3c393/move' \
  -X 'POST' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6' \
  -H 'Authorization: Bearer b6c17be4-a2ee-4a39-9e5e-91a2bb5521ee' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 0' \
  -H 'Origin: http://localhost:3003' \
  -H 'Referer: http://localhost:3003/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-pla

![photo_2024-09-19_21-37-03](https://github.com/user-attachments/assets/64f51114-1139-41ba-b4bb-088edc05599c)
tform: "Windows"'

**Comment by JSDID** [comment]
curl 'https://app.admss.com/api/v1/reports/33e88d0e-fa44-4e1d-a279-e8a72f9bbbbb/collection' \
-X 'POST' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json, text/plain, */*' \
-H 'Authorization: Bearer d4150184-2ce7-4bf3-a614-554e943bc1fa' \
-H 'Sec-Fetch-Site: cross-site' \
-H 'Accept-Language: en-US,en;q=0.9' \
-H 'Accept-Encoding: gzip, deflate, br' \
-H 'Sec-Fetch-Mode: cors' \
-H 'Host: app.admss.com' \
-H 'Origin: http://localhost:3003' \
-H 'Content-Length: 379' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15' \
-H 'Referer: http://localhost:3003/' \
-H 'Connection: keep-alive' \
-H 'Sec-Fetch-Dest: empty' \
--data-binary '{"name":"tc3","documents":[{"AskForStartAndEndDates":0,"ShowAverages":0,"ShowLineCount":0,"ShowTotals":0,"count":1,"created":"09/18/2024 19:07:26","documentUID":"bef4e179-e4bd-4ac7-bee8-16750a6df431","index":94,"isfavorite":0,"itemUID":"7ae636c0-5e97-4ca6-915a-f11454c75c0b","name":"18-09-22:06","updated":"09/18/2024 19:07:26"}],"itemuid":"e61525a1-54c2-4f82-b232-0b784eb7f76c"}'

**Comment by JSDID** [comment]
Это я пробую текущую коллекцию отредактировать, но старая при этом остается, и создается новая с теми данными, которые я указал (id редактируемой коллекции в запросе есть)

**Comment by JSDID** [comment]
Редактирование вчера не работало, а сегодня создает новую коллекцию, хотя я отправляю ей id редактируемой коллекции
