### ISSUE TITLE
Доступ к инвентории

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#623]
При попытки открыть инвенторию на пользователи loadtest (password) у меня она не открывается, а появляется пустое окно

![image](https://github.com/user-attachments/assets/41237cdc-799d-4223-850a-dea1e9ee7f37)

**Comment by kamabzalov** [comment]
@JSDID 
теперь у этого пользователя не открываются другие разделы, всегда бросает на главный экран. А инвентория открывается

[Uploading Screencast_from_2024-09-20_21-00-21.webm…]()

**Comment by JSDID** [comment]
> @JSDID 
> теперь у этого пользователя не открываются другие разделы, всегда бросает на главный экран. А инвентория открывается
> 
> [Screencast_from_2024-09-20_21-00-21.webm](https://github.com/user-attachments/assets/ffbb563b-f9fd-42e3-af75-5cff7542e2b7)
> 
> 


потому что у него salesperson: 1

было сказано, если salesperson: 1 - допускать только к инвенториям

**Comment by JSDID** [comment]
![IMG_20240920_223512_256.jpg](https://github.com/user-attachments/assets/b420ca11-9c8c-421d-9a15-cfff7d5cf042)

**Comment by kamabzalov** [comment]
@JSDID 
переход в создание не пускает

![image](https://github.com/user-attachments/assets/d804ea9d-6efb-4a7d-b9cd-4ead3ccb926f)
