### ISSUE TITLE
Export to WEB цена

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#630]
Добавить возможность сменить цену в таблице листа экспорта. Также добавить окно подтверждения действия, чтобы случайно не менялась цена

[Screencast_from_2024-09-03_18-48-26.webm](https://github.com/user-attachments/assets/39edec4e-b9f0-4968-91b4-d2416950f960)
Если вводить цену в целых числах, например 500 - то так и сохраняет, и только через секунду приписывает .00 - было бы красивее, если бы эти целые появлялись без задержки. И сами мы можем ввести бесконечное кол-во знаком после запятой, и так и сохраняет, а через секунду обрезает - опять таки лучше не позволять сразу вводить больше 2 знаков после запятой

**Comment by kamabzalov** [comment]
@JSDID 
появился новый дизай колонк, а также модальное окно подтверждения о смене цены

[auto dealer](https://www.figma.com/design/BDg0gIw134tMRsEwMUa3G4/auto-dealer?node-id=7100-25611&t=kbo04sszlnsdvqiz-4)

**Comment by kamabzalov** [comment]
@JSDID уже протестили:
"Когда мы меняем цену и появляется модальное окно, я нажимаю на крестик - окно закрывается, а цена уже сменилась, хотя я не подтверждала данное действие"

**Comment by kamabzalov** [comment]
@JSDID 
Мы почему-то цену расписываем во все инпуты
![image](https://github.com/user-attachments/assets/770f4571-45f9-4cd4-99b7-b198b724adf6)

**Comment by JSDID** [comment]
> @JSDID Мы почему-то цену расписываем во все инпуты ![image](https://private-user-images.githubusercontent.com/49127222/376703309-770f4571-45f9-4cd4-99b7-b198b724adf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMTA1MDcsIm5iZiI6MTcyOTAxMDIwNywicGF0aCI6Ii80OTEyNzIyMi8zNzY3MDMzMDktNzcwZjQ1NzEtNDVmOS00Y2Q0LTk5YjctYjE5OGI3MjRhZGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE2MzY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYjRhOWM2NzQwYWUxYzUyZmNkM2E0MmQ1OTk5YzRhMDc4Mjg5YmQ1Zjk2NGYzMDIwYjFiNDM0NDZiM2U2MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AC-b_KoeGh5YfXA2O93f9lYjcF3tgMyxc7_v30Nnhbs)

Сервисы? Так и было задумано. Изначально в сервисах цена копирует цену ListPrice, а потом уже можно ее изменять

**Comment by kamabzalov** [comment]
@JSDID, от тестировщицы и клиента 
"После того, как я меняю цену, она меняется и в сервисах, но там она не должна меняться, как мы обговорили на звонке"

**Comment by kamabzalov** [comment]
@JSDID от тестировщицы:

Я сменила цену в первой записи и все гуд. Я меняю цену на 3 записи с 0 на 2, нажимаю отменить на окне подтверждения и цена сама меняется на 12

**Comment by kamabzalov** [comment]
@JSDID 
Надо иметь возможность ввести с центами

**Comment by kamabzalov** [comment]
@JSDID 
![image](https://github.com/user-attachments/assets/585b67e9-3765-4165-aa72-a04a3f70b383)

надо расширить поле цены, иначе я не вижу полную сумму. Если цена в целых числах, то надо .00 приписывать, чтобы красиво было)
