### ISSUE TITLE
Создание инвентории с дублируещимся ВИН номером

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#634]
Если у нас дублируется сток номер, мы это валидируем на фронте и показываем ошибку. При дубликате ВИН номера мы ошибку не отображаем и позволяем создавать инвенторию в результате получая 422. Предлагаю сделать такую же проверку как и со сток номером

![image](https://github.com/user-attachments/assets/3c35c198-7dc8-4c5c-a8fc-676e6b45373c)

![image](https://github.com/user-attachments/assets/5c1f6fd5-b10d-4037-918f-3eb8b00e295f)

**Comment by JSDID** [comment]
По 631 я перепроверил на разных экранах - все ок. 32vh как раз пр
![photo_2024-09-24_21-17-03 (2)](https://github.com/user-attachments/assets/1ca4ee92-87bc-4212-afb9-2e3a376b64b9)
![photo_2024-09-24_21-17-03](https://github.com/user-attachments/assets/109568a4-5129-42f0-be62-f98ac8c15465)
авильное значение

**Comment by JSDID** [comment]
При валидации stock number у нас отправляется запрос на отдельный ендпоинт /api/v1/inventory/stocknumber, который возвращает нам exists: 1или 0, для vin у нас такого ендпоинта - нет (по крайней мере в swagger)

Поэтому мы не можем провести валидацию VIN до отправки формы инвентории

![photo_2024-09-24_21-26-17 (2)](https://github.com/user-attachments/assets/612055d0-69ff-4b4c-90f7-b248c2dc618e)
![photo_2024-09-24_21-26-17](https://github.com/user-attachments/assets/e44e7792-c91e-40d3-a5ea-cfc73071d4fa)
![photo_2024-09-24_21-26-17 (3)](https://github.com/user-attachments/assets/efe7d973-7394-4e75-a4ef-4f4ee16d8013)
![photo_2024-09-24_21-26-17 (4)](https://github.com/user-attachments/assets/41098f6f-50eb-4b1e-a881-3f28fe4078b3)

**Comment by kamabzalov** [comment]
@JSDID 
добавлено на бэк и в сваггер

GET /api/v1/inventory/{vincode}/checkvin

**Comment by JSDID** [comment]
Работает проверка через АПИ странно. Сервер на mobile2 при вводе существующего VIN отвечает exists: 1 и возвращает ошибку, а на testuser1 всегда возвращает exists: 0 - я пробовал разные VIN существующие брать, и все равно было всегда exists: 0, соответственно ошибки не было

**Comment by kamabzalov** [comment]
@JSDID АПИ исправлено. Проверьте

**Comment by JSDID** [comment]
Это работает

**Comment by kamabzalov** [comment]
@JSDID 
при вводе вин номера, фронт сам удаляет данные, что я ввожу 
[Screencast_from_2024-10-01_19-00-26.webm](https://github.com/user-attachments/assets/400fe23d-7e7b-4231-8a27-794a35a29716)
