### ISSUE TITLE
Чекбоксы в Export to WEB

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#635]
[Screencast_from_2024-09-05_19-15-39.webm](https://github.com/user-attachments/assets/59d5f182-7c9b-4c50-98e5-a4adaceab60c)

Если нажать на 1 чекбокс у конкретной записи, выбираются сразу все чекбоксы. Если нажать на чекбокс у названия колонки, то все чекбоксы слетают, если нажать еще раз, то выбирается только чекбокс у названия колоноки.

**Comment by JSDID** [comment]
Исправлено. Таска не актуальна. Сейчас такого поведения (как на видео) нет.
