### ISSUE TITLE
OFAC

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#651]
Добавить модальное окно, при создании юзера, если OFAC уже нашел такую персону и прислал по ней данные. По нажатию на ОК мы переходим в раздел OFAC

дизайн: https://www.figma.com/design/BDg0gIw134tMRsEwMUa3G4/auto-dealer?node-id=7036-31788&t=8li6mfAghQJPBGur-4

**Comment by JSDID** [comment]
Откуда его читать и в каком виде отображать?

**Comment by kamabzalov** [comment]
@JSDID 
POST /api/v1/contacts/{contactuid}/check - if contactuid is 0 check from payload ( OFAC)

также при апдейте или создании контакта бэк атоматом проверяет OFAC
результат возвращается в поле “OFAC“

в сваггере прописано

**Comment by JSDID** [comment]
Нам swagger показывает что мы получим большой ответ, но по факту приходит совсем другое (всего 3 поля +у всех контактов одинаковые).

![photo_2024-10-03_09-36-21](https://github.com/user-attachments/assets/b2b532d3-d322-4803-8463-15d20545a185)
![photo_2024-10-03_09-36-21 (2)](https://github.com/user-attachments/assets/72d97eea-6d60-4dd1-8ff6-84d435aa61c1)
![photo_2024-10-03_09-36-21 (3)](https://github.com/user-attachments/assets/4a4c4a34-7274-42b0-bc30-b1c1afb1eca5)

**Comment by JSDID** [comment]
Я пока это все отображаю в таком виде (что-бы просто показать ответ), так как ответ совсем не похож, на то что нарисовано в дизайне.

![photo_2024-10-03_09-37-29](https://github.com/user-attachments/assets/d90754c7-e91d-4b23-b264-ce6c39cd52a3)

**Comment by JSDID** [comment]
Не совсем понятно в каком виде должен и куда уходить payload. Я правильно понял, что при нажатии "Scan driver license" нужно отправить файл (.png, .jpeg) на какой-то ендпоинт, И если от сервера пришел ответ, которые говорит что эти данные уже есть (как нам понять, что данные есть? Какое поле?), после этого перекинуть на вкладку (табу) OFAC?

![photo_2024-10-03_09-50-10](https://github.com/user-attachments/assets/c6fc4df5-e0e3-4d02-9ed6-812a9ab5038e)

**Comment by kamabzalov** [comment]
@JSDID 

Поправлено в апдейте

Если chek НЕ пройден,
то вернётся больше данных

```
jRet["check_status"] = "FAILED";
jRet["created"] = milliseconds2String( ofac.created, false);
    jRet["updated"] = milliseconds2String( ofac.updated, false);
    jRet["listid"] = ofac.idx;
    jRet["dob"] = ofac.dob;
    jRet["firstname"] = ofac.firstname;
    jRet["lastname"] = ofac.lastname;
    jRet["details"] = [ofac.info](http://ofac.info "‌");
```

то что в “details“ надо показать в окошке, как в дизайне нарисовано

**Comment by JSDID** [comment]
Возможно есть запись (контакт) где есть другой ответ, но я перещелкал пару десятков, ответ везде один и тот же
![photo_2024-10-05_19-14-12](https://github.com/user-attachments/assets/bb95ca88-8d7f-4db2-9701-f2ada048c7a3)

**Comment by JSDID** [comment]
curl 'https://app.admss.com/api/v1/contacts/565b47d0-9cd0-423a-b9ee-71bf6f2a08cf/check' \
  -X 'POST' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6' \
  -H 'Authorization: Bearer bf02fb3d-c5af-4aad-b109-4033d80f88c0' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 0' \
  -H 'Origin: http://localhost:3003' \
  -H 'Referer: http://localhost:3003/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"'

curl 'https://app.admss.com/api/v1/contacts/f7b7cffa-e204-4d86-94a1-950191018617/check' \
  -X 'POST' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6' \
  -H 'Authorization: Bearer f10e4e08-1172-4d96-89c8-5774312c1b68' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 0' \
  -H 'Origin: http://localhost:3003' \
  -H 'Referer: http://localhost:3003/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"'

**Comment by kamabzalov** [comment]
@JSDID бэк пишет:
Попробуйте этого - Jabril, Ahmad

**Comment by kamabzalov** [comment]
> @JSDID бэк пишет: Попробуйте этого - Jabril, Ahmad

Попробовать создать юзера с этим ФИО

**Comment by JSDID** [comment]
> > @JSDID бэк пишет: Попробуйте этого - Jabril, Ahmad
> 
> Попробовать создать юзера (контакт) с этим ФИО

Тоже самое. OFAC возвращает всегда один и тот же ответ![IMG_20241007_102744_865.jpg](https://github.com/user-attachments/assets/71460806-5a09-4870-a62e-bcb67c04116c)

**Comment by kamabzalov** [comment]
@JSDID бэк уточняет
Ahmad - это имя
Jabril - фамилия

**Comment by JSDID** [comment]
Ответ есть, но как мне с этого сделать то, что в дизайне? Там полотно текста, а тут несколько слов.

![IMG_20241008_172258_261.jpg](https://github.com/user-attachments/assets/eeb132a5-6f9b-449c-85d0-87977d4be30a)
