### ISSUE TITLE
Кнопка удаления контакта

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#672]
Добавить кнопку удаления контакта

![image](https://github.com/user-attachments/assets/b329951d-7084-4c08-b116-e8236b325b49)

Или посмотрите в figma

**Comment by JSDID** [comment]
curl 'https://app.admss.com/api/v1/contact/7e384def-663b-4eb9-bb6c-d5edebcdeaad/delete' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'Authorization: Bearer 9ea1c067-395f-4be5-9fe8-2a099189f875' \
  -H 'Referer: http://localhost:3003/' \
  -H 'sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Content-Type: application/json' \
  --data-raw '{"reason":"Cleanup","comment":""}'

**Comment by JSDID** [comment]
Все так же CORS

**Comment by kamabzalov** [comment]
@JSDID попробуйте, вызывать метод
POST /api/v1/contacts/{contactuid}/deletecontact

**Comment by JSDID** [comment]
curl 'https://app.admss.com/api/v1/contact/7e384def-663b-4eb9-bb6c-d5edebcdeaad/deletecontact' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'Authorization: Bearer 48fa7a6c-8124-4e82-a4eb-590fe87f86fe' \
  -H 'Referer: http://localhost:3003/' \
  -H 'sec-ch-ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Content-Type: application/json' \
  --data-raw '{"reason":"Cleanup","comment":"test"}'

![photo_2024-10-20_19-19-24](https://github.com/user-attachments/assets/dcea62da-204f-4848-881f-383dbde23a06)

**Comment by JSDID** [comment]
тоже самое и с другим методом)

**Comment by JSDID** [comment]
Удаление все так же не работает. CORS. Вот только что проверил

![photo_2024-10-21_21-30-42](https://github.com/user-attachments/assets/5a4a6e4b-3949-4911-af66-69a7d4579762)

**Comment by JSDID** [comment]
curl 'https://app.admss.com/api/v1/contact/7e384def-663b-4eb9-bb6c-d5edebcdeaad/deletecontact' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'Authorization: Bearer 78c09224-9dc8-4cc8-992c-38881c341972' \
  -H 'Referer: http://localhost:3003/' \
  -H 'sec-ch-ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Content-Type: application/json' \
  --data-raw '{"reason":"Information is outdated","comment":""}'

**Comment by JSDID** [comment]
curl 'https://app.admss.com/api/v1/contact/7e384def-663b-4eb9-bb6c-d5edebcdeaad/deletecontact' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'Authorization: Bearer 78c09224-9dc8-4cc8-992c-38881c341972' \
  -H 'Referer: http://localhost:3003/' \
  -H 'sec-ch-ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Content-Type: application/json'

**Comment by JSDID** [comment]
curl 'https://app.admss.com/api/v1/contact/7e384def-663b-4eb9-bb6c-d5edebcdeaad/delete' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'Authorization: Bearer 78c09224-9dc8-4cc8-992c-38881c341972' \
  -H 'Referer: http://localhost:3003/' \
  -H 'sec-ch-ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Content-Type: application/json' \
  --data-raw '{"reason":"Duplicated record","comment":""}'

**Comment by JSDID** [comment]
curl 'https://app.admss.com/api/v1/contact/7e384def-663b-4eb9-bb6c-d5edebcdeaad/delete' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'Authorization: Bearer 78c09224-9dc8-4cc8-992c-38881c341972' \
  -H 'Referer: http://localhost:3003/' \
  -H 'sec-ch-ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Content-Type: application/json'

**Comment by JSDID** [comment]
![photo_2024-10-24_22-21-11](https://github.com/user-attachments/assets/90c07caa-7310-4561-adf7-d9214f2a4337)

**Comment by JSDID** [comment]
![photo_2024-10-24_22-21-53](https://github.com/user-attachments/assets/dec58e1c-399c-46de-b8df-2a26c1a15c4a)
)
