### ISSUE TITLE
Создание/обновление инвентории

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#692]
Если зайти на персону mobile2 и найти инвенторию в вин номером 2C4RDGCGOFR805928 - мы увидим, что все поля заполнены, я пытаюсь изменить вин, но мне не дает сохранить подсвечивая раздел description, что какое-то поле там пустое. Они все заполнены
![image](https://github.com/user-attachments/assets/6115cb50-3cd7-4413-8387-08f762b771b1)

После создания инвентории, если открыть форму создания новой локация остается пустой, хотя там должна быть дефолтная
![image](https://github.com/user-attachments/assets/54422d7c-405d-4236-bd86-02e3a6624a63)

**Comment by JSDID** [comment]
По поводу локации детально описал в задаче https://github.com/kamabzalov/admss-client/issues/693

**Comment by kamabzalov** [comment]
@JSDID а локация тут причем?

**Comment by kamabzalov** [comment]
@JSDID 
Теперь поле топлива изначально заполнено
![image](https://github.com/user-attachments/assets/82cd96b2-eb20-45bb-84b7-dbdf7a10b430)

Но так как поле находится не на первом разделе, пользователь может туда не дойти и по ошибки сохранить неверную информацию. Все же стоит оставить его пустым, как это сделано например с полем inventory group - оно изначально пустое
