### ISSUE TITLE
Год и локации в инвентории

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#693]
После создание инвентории локация остается пустой, хотя в апи она приходит

Сделать поле года обязательным

**Comment by JSDID** [comment]
![photo_2024-10-25_18-19-48](https://github.com/user-attachments/assets/f1c2eb84-a259-4f89-abbf-b24798a4cb33)

Вот 2 локации которые нам приходят как опции в dropdown.

![photo_2024-10-25_18-20-42](https://github.com/user-attachments/assets/74a10a30-1033-4e9b-9197-80ea6016fb6d)

А вот id локации, которая нам приходит в https://app.admss.com/api/v1/inventory/1a8e259f-1632-4496-a5cc-c2427ca0386b/info

**Comment by JSDID** [comment]
Соответственно dropdown не находит опции с таким id, и поле остается пустым.

**Comment by JSDID** [comment]
curl 'https://app.admss.com/api/v1/user/d51ffe3a-10d3-497e-a4d2-61894dae2b2e/locations' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6' \
  -H 'Authorization: Bearer 7103684f-a974-4c68-90ed-352b36e1792e' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:3003' \
  -H 'Referer: http://localhost:3003/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"'

**Comment by JSDID** [comment]
curl 'https://app.admss.com/api/v1/inventory/1a8e259f-1632-4496-a5cc-c2427ca0386b/info' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6' \
  -H 'Authorization: Bearer 7103684f-a974-4c68-90ed-352b36e1792e' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:3003' \
  -H 'Referer: http://localhost:3003/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"'

**Comment by JSDID** [comment]
Пользователь: mobile2, инвентория на котором обнаружено несоотвествие id локаций: /dashboard/inventory/1a8e259f-1632-4496-a5cc-c2427ca0386b

**Comment by JSDID** [comment]
Если id локаций совпадают - поле работает как положено, т.е. запоняется.
