### ISSUE TITLE
Payments in inventory

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#755]
в Purchase → Payments мы должны вызывать апи POST /api/v1/inventory/{id}/expense - set items's expense
В Purchase → Expenses - значения для дропа Type мы должны получать с этого апи м

**Comment by JSDID** [comment]
С какого АПИ?

**Comment by kamabzalov** [comment]
@JSDID 
бэк дал неверный апи

GET /api/v1/inventory/{inventoryuid}/paymentpack
POST /api/v1/inventory/{inventoryuid}/paymentpack

сваггер и бэк проапдейчены

**Comment by JSDID** [comment]
А для чего нам нужен этот ендпоинт? Я думал, что он нам возращает массив записей, но согласно swagger он возвращает одну запись. Для чего она нам нужна?

![photo_2024-11-27_18-42-38](https://github.com/user-attachments/assets/d46af9c8-a23a-4fcb-8334-8242040e262b)

**Comment by kamabzalov** [comment]
@JSDID отправил вопрос

**Comment by kamabzalov** [comment]
@JSDID 
Верхнюю часть формы заполнить

Где вы сам стрелочки рисовали красные

**Comment by JSDID** [comment]
![photo_2024-11-28_18-53-24](https://github.com/user-attachments/assets/260830d9-c5de-47cb-b2e2-3afe9cfe43c0)
![photo_2024-11-28_15-36-56](https://github.com/user-attachments/assets/f795047e-eafd-48be-a0a4-406cb46058b3)

Не работает предовтавленное АПИ. POST возвращает ошибку, а GET возвращает только STATUS в ответе (хотя согласно swagger там должны быть все поля)

**Comment by JSDID** [comment]
GET curl 'https://app.admss.com/api/v1/inventory/691590e0-ac4f-462f-8d8e-c9294a8e5237/paymentpack' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6' \
  -H 'Authorization: Bearer ff51f36c-f3df-4782-8ce8-9283dd96fad9' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:3003' \
  -H 'Referer: http://localhost:3003/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"'

**Comment by JSDID** [comment]
POST curl 'https://app.admss.com/api/v1/inventory/691590e0-ac4f-462f-8d8e-c9294a8e5237/paymentpack' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6' \
  -H 'Authorization: Bearer ff51f36c-f3df-4782-8ce8-9283dd96fad9' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://localhost:3003' \
  -H 'Referer: http://localhost:3003/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{"payPack":0,"payDefaultExpAdded":1,"payPaid":0,"paySalesTaxPaid":0,"payRemarks":"test"}'

**Comment by kamabzalov** [comment]
@JSDID исправлено

**Comment by JSDID** [comment]
По paymentpack АПИ заработало (и чтение и запись)

Но что делать сейчас с этим АПИ (для таблицы), которое не работает? Или это будет отдельная задача?

![photo_2024-11-29_15-48-05](https://github.com/user-attachments/assets/c5b3341a-1a69-46fa-a9ee-011a399a4a4a)

**Comment by JSDID** [comment]
Здесь как?

**Comment by kamabzalov** [comment]
@JSDID я отпишу ответ

**Comment by kamabzalov** [comment]
> Здесь как?

@JSDID  там надо вызывать expenses

**Comment by JSDID** [comment]
> > Здесь как?
> 
> @JSDID там надо вызывать expenses

Сделано

**Comment by kamabzalov** [comment]
@JSDID от бэка:

я был не совсем прав

Для таблички используй, плиз

GET /api/v1/inventory/{inventoryuid}/paymentpack

Пока там будет только одна запись

**Comment by JSDID** [comment]
Значения есть, но в дизайне у нам там суммы, текст а в ответе сервера только 0 или 1.  Или текс будет изменяться в зависимости от этих 0/1?
![photo_2024-12-03_16-46-13](https://github.com/user-attachments/assets/00878b63-2775-40eb-8ac7-37128753e38b)
![photo_2024-12-03_16-46-14](https://github.com/user-attachments/assets/ada61fe3-5243-415d-be66-3776f3e18201)

**Comment by kamabzalov** [comment]
@JSDID 
Там признак 0\1 учтены ли дефолтные экспенсы, а не сумма

**Comment by JSDID** [comment]
> @JSDID 
> Там признак 0\1 учтены ли дефолтные экспенсы, а не сумма

Я говорю за все 4 колонки. Сравнить их с тем, что в дизайне, и то что приходит в ответе от сервера. Как мне например сделать с defaultExpense: 0/1 текст, который показан в дизайне (Data from Database)

**Comment by kamabzalov** [comment]
@JSDID просьба колонку Default expenses отрисовывать как readonly checkbox: 1 - checked, 0 - unchecked

**Comment by kamabzalov** [comment]
@JSDID 

При сохранении payments, y нас вызывавется запрос
curl 'https://app.admss.com/api/v1/accounts/c57d4e70-017a-42a4-a72b-a42637415c5f/payments' 
-H 'Accept: application/json, text/plain, /' 
-H 'Accept-Language: en-US,en;q=0.9' 
-H 'Authorization: Bearer 58e048c9-0e26-497d-8e3f-0e6aba302deb' 
-H 'Cache-Control: no-cache' 
-H 'Connection: keep-alive' 
-H 'Origin: https://app.admss.com:3002'/ 
-H 'Pragma: no-cache' 
-H 'Referer: https://app.admss.com:3002/' 
-H 'Sec-Fetch-Dest: empty' 
-H 'Sec-Fetch-Mode: cors' 
-H 'Sec-Fetch-Site: same-site' 
-H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' 
-H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' 
-H 'sec-ch-ua-mobile: ?0' 
-H 'sec-ch-ua-platform: "Linux"'

 

который возвращает 422, потому что вы это вызываем из инвентории и аккаунта тут никакого нет.

Надо было же заменить запрос на GET /api/v1/inventory/{inventoryuid}/paymentpack - разве нет?

**Comment by kamabzalov** [comment]
@JSDID 

При сохранении payments, y нас вызывавется запрос
curl 'https://app.admss.com/api/v1/accounts/c57d4e70-017a-42a4-a72b-a42637415c5f/payments' 
-H 'Accept: application/json, text/plain, /' 
-H 'Accept-Language: en-US,en;q=0.9' 
-H 'Authorization: Bearer 58e048c9-0e26-497d-8e3f-0e6aba302deb' 
-H 'Cache-Control: no-cache' 
-H 'Connection: keep-alive' 
-H 'Origin: https://app.admss.com:3002'/ 
-H 'Pragma: no-cache' 
-H 'Referer: https://app.admss.com:3002/' 
-H 'Sec-Fetch-Dest: empty' 
-H 'Sec-Fetch-Mode: cors' 
-H 'Sec-Fetch-Site: same-site' 
-H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' 
-H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' 
-H 'sec-ch-ua-mobile: ?0' 
-H 'sec-ch-ua-platform: "Linux"'

 

который возвращает 422, потому что вы это вызываем из инвентории и аккаунта тут никакого нет.

Надо было же заменить запрос на GET /api/v1/inventory/{inventoryuid}/paymentpack - разве нет?

**Comment by JSDID** [comment]
> @JSDID
> 
> При сохранении payments, y нас вызывавется запрос curl 'https://app.admss.com/api/v1/accounts/c57d4e70-017a-42a4-a72b-a42637415c5f/payments' -H 'Accept: application/json, text/plain, /' -H 'Accept-Language: en-US,en;q=0.9' -H 'Authorization: Bearer 58e048c9-0e26-497d-8e3f-0e6aba302deb' -H 'Cache-Control: no-cache' -H 'Connection: keep-alive' -H 'Origin: https://app.admss.com:3002'/ -H 'Pragma: no-cache' -H 'Referer: https://app.admss.com:3002/' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-site' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' -H 'sec-ch-ua-mobile: ?0' -H 'sec-ch-ua-platform: "Linux"'
> 
> который возвращает 422, потому что вы это вызываем из инвентории и аккаунта тут никакого нет.
> 
> Надо было же заменить запрос на GET /api/v1/inventory/{inventoryuid}/paymentpack - разве нет?

Так заменено. У меня все корректно вызывает)

![photo_2024-12-10_19-26-12](https://github.com/user-attachments/assets/499abe30-a31a-4b75-bb97-258c55c6d786)

**Comment by kamabzalov** [comment]
@JSDID надо Paid и Sales taxes paid заменить на чекбоксы
