### ISSUE TITLE
Advanced search in contact

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#766]
Кнопка Advanced search в контактах не работает

**Comment by JSDID** [comment]
Нужно у бека уточнить названия полей. которые нужно отправлять для выборки

![photo_2024-11-29_20-21-57](https://github.com/user-attachments/assets/f40c9c82-a313-44a3-b876-56a100ede64c)

**Comment by JSDID** [comment]
Здесь надо с нуля писать

**Comment by kamabzalov** [comment]
@

**Comment by kamabzalov** [comment]
@JSDID 
![image](https://github.com/user-attachments/assets/4636a732-64a9-400b-a3a8-93025170ae78)

запрос формируется по аналогии с инвентори

по полям
username, lastname, phone1,
тип контакта передаём в URL как param=<type_as_int>

**Comment by JSDID** [comment]
Бек дал не правильное инфо. У нас нет полей в форме в дизайне поиск по first/last name, а только по полному имени это 1, и второе в форме есть тип. Попробую отправлять как type

![IMG_20241201_170424_038.jpg](https://github.com/user-attachments/assets/cc74e928-87fc-43d3-8dfb-35112f3267dc)

**Comment by kamabzalov** [comment]
> Бек дал не правильное инфо. У нас нет полей в форме в дизайне поиск по first/last name, а только по полному имени это 1, и второе в форме есть тип. Попробую отправлять как type
> 
> ![IMG_20241201_170424_038.jpg](https://private-user-images.githubusercontent.com/102165823/391341629-cc74e928-87fc-43d3-8dfb-35112f3267dc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNjg2MDIsIm5iZiI6MTczMzA2ODMwMiwicGF0aCI6Ii8xMDIxNjU4MjMvMzkxMzQxNjI5LWNjNzRlOTI4LTg3ZmMtNDNkMy04ZGZiLTM1MTEyZjMyNjdkYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxNTUxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODhkYjk2ZjVlNDFlNWU4M2U0MDhmN2FiNDJmZWUzMTdkZjg2NThiNWU5OGVkYzhjMGFiMGVhMjI5OThlNGQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NIuFycebP-GSAi6HdHuu76MYR1A8HoVWYq99rBBxEaY)

Зачем как type? Если бэк дал неправильное - значит либо дизайн либо бэк будут исправлять

**Comment by JSDID** [comment]
> > Бек дал не правильное инфо. У нас нет полей в форме в дизайне поиск по first/last name, а только по полному имени это 1, и второе в форме есть тип. Попробую отправлять как type
> > ![IMG_20241201_170424_038.jpg](https://private-user-images.githubusercontent.com/102165823/391341629-cc74e928-87fc-43d3-8dfb-35112f3267dc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNjg2MDIsIm5iZiI6MTczMzA2ODMwMiwicGF0aCI6Ii8xMDIxNjU4MjMvMzkxMzQxNjI5LWNjNzRlOTI4LTg3ZmMtNDNkMy04ZGZiLTM1MTEyZjMyNjdkYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxNTUxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODhkYjk2ZjVlNDFlNWU4M2U0MDhmN2FiNDJmZWUzMTdkZjg2NThiNWU5OGVkYzhjMGFiMGVhMjI5OThlNGQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NIuFycebP-GSAi6HdHuu76MYR1A8HoVWYq99rBBxEaY)
> 
> Зачем как type? Если бэк дал неправильное - значит либо дизайн либо бэк будут исправлять

type работает. Он нам нужен. и он работает

**Comment by JSDID** [comment]
У нас сейчас проблема с Contact Name. У нас в дизайне только одно это поле. А нам нужно что бы бек отдавал и найденные по имени+фамилия и по имени компании.

**Comment by JSDID** [comment]
Поиск по первому полю не работает

**Comment by kamabzalov** [comment]
Кстати, а где вы видите firstName, lastName?

**Comment by kamabzalov** [comment]
> @JSDID ![image](https://private-user-images.githubusercontent.com/49127222/391275188-4636a732-64a9-400b-a3a8-93025170ae78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzkwMzIsIm5iZiI6MTczMzA3ODczMiwicGF0aCI6Ii80OTEyNzIyMi8zOTEyNzUxODgtNDYzNmE3MzItNjRhOS00MDBiLWEzYTgtOTMwMjUxNzBhZTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDE4NDUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxOWIxMDkzM2U4NTg2MzZhNmU5ZTJiZjg4NzFiYWQxNTViMTIzZjM5NjY0YWUwYjMzNTA5NDU0NmIxNTljZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H2M1TRdDt6JhfmUzRWwOlX62GT_IXQPTneuhdmqwmhI)
> 
> запрос формируется по аналогии с инвентори
> 
> по полям username, lastname, phone1, тип контакта передаём в URL как param=<type_as_int>

Где здесь contactName?

**Comment by kamabzalov** [comment]
@JSDID  еще раз уточнил у бэка - lastName - это лишнее

**Comment by kamabzalov** [comment]
@JSDID 

1. Если выбрать тип. то его потом нельзя убрать. Нажимаю на крестик, а он остается.
2. Думаю надо для номера телефона добавить валидацию, чтобы только цифры вводили

**Comment by JSDID** [comment]
> @JSDID Если вводить больше цифр, чем американский номер, то последние цифры меняются на 0
> 
> ![image](https://private-user-images.githubusercontent.com/49127222/392693860-a39e719b-1863-4f83-ae7b-c06ca5bc04a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MTk5MzEsIm5iZiI6MTczMzQxOTYzMSwicGF0aCI6Ii80OTEyNzIyMi8zOTI2OTM4NjAtYTM5ZTcxOWItMTg2My00ZjgzLWFlN2ItYzA2Y2E1YmMwNGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE3MjcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyYTVkOWFlYzJjMjY3ZmUzMjgwNjg4ZGE3NDk2MmFjZDQxMmY4NjU0ZDA1MzUwYjEwOWY1MzI3ZGM0MzI3MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v7pCAvV7wnYMvWRAoZN3_81jb4AhJrt1agLof1rUM7c)

А нам тут лучше ограничить кол-во вводимых символов или просто не заменять на 0?

**Comment by kamabzalov** [comment]
Конечно ограничить. Как номер телефона может быть ограниченной длины
Посомтрите в других формах, где есть номер телефона

**Comment by kamabzalov** [comment]
https://support.telesign.com/s/article/what-is-the-maximum-length-of-any-phone-number#:~:text=In%20the%20United%20States%20and,be%20longer%20than%2015%20digits.

**Comment by kamabzalov** [comment]
https://chatgpt.com/c/6751e3a7-6cf0-800e-823c-c0bdcb50c48c

**Comment by JSDID** [comment]
Ограничил

**Comment by JSDID** [comment]
https://github.com/user-attachments/assets/aaeb4060-a5bf-4879-ab7e-9a4d4c7085af

**Comment by JSDID** [comment]
Просто тут ни слова не сказано про ограничить, а описана проблема нулей. Потому я и уточнил.
