### ISSUE TITLE
Advanced search в инвентории

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#774]
В инвентории не происходит поиск по марке машины

curl '[https://app.admss.com/api/v1/inventory/57b60d65-1eed-4fdf-80d8-02fdcc45bbe7/list?first=0&rows=1000&page=1&sortField=Make&sortOrder=1&qry=BMW.Make'](https://app.admss.com/api/v1/inventory/57b60d65-1eed-4fdf-80d8-02fdcc45bbe7/list?first=0&rows=1000&page=1&sortField=Make&sortOrder=1&qry=BMW.Make%27) 
-H 'sec-ch-ua-platform: "Windows"' 
-H 'Authorization: Bearer 8890b56b-bc01-442b-8c98-0416b626b4eb' 
-H 'Referer: https://app.admss.com:3002/' 
-H 'Accept-Language: ru' 
-H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' 
-H 'sec-ch-ua-mobile: ?0' 
-H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' 
-H 'Accept: application/json, text/plain, /'

откуда в запросе
[first=0&rows=1000&page=1&sortField=Make&sortOrder=1](https://app.admss.com/api/v1/inventory/57b60d65-1eed-4fdf-80d8-02fdcc45bbe7/list?first=0&rows=1000&page=1&sortField=Make&sortOrder=1&qry=BMW.Make%27) ???

у нас другие параметры для фильтрации и пагинации

Надо сравнить с контактами (там advanced search вроде в порядке)

**Comment by JSDID** [comment]
https://github.com/kamabzalov/admss-client/issues/774 у меня того что написано в задаче нет.

**Comment by JSDID** [comment]
curl 'https://app.admss.com/api/v1/inventory/d51ffe3a-10d3-497e-a4d2-61894dae2b2e/list?first=0&rows=20&page=1&qry=AUDI.Make%252B100.Model' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6' \
  -H 'Authorization: Bearer 44cabad9-a1e1-4ee3-a6e5-d2b5bfa02d00' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:3003' \
  -H 'Referer: http://localhost:3003/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"'

**Comment by kamabzalov** [comment]
А sortField, sortOrder

**Comment by kamabzalov** [comment]
@JSDID и еще посмотрите - в какой задаче они появились?

**Comment by kamabzalov** [comment]
@JSDID также сравните с contacts/deals и пр

**Comment by JSDID** [comment]
curl 'https://app.admss.com/api/v1/inventory/d51ffe3a-10d3-497e-a4d2-61894dae2b2e/list?first=0&rows=20&page=1&qry=AUDI.Make%252B100.Model' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6' \
  -H 'Authorization: Bearer 44cabad9-a1e1-4ee3-a6e5-d2b5bfa02d00' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:3003' \
  -H 'Referer: http://localhost:3003/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"'

Это contact отправляем

 [IMG_20241207_132506_610.jpg](https://github.com/user-attachments/assets/0c99f9a4-fb20-49a9-8872-dc8b2c584a95)

![IMG_20241207_132510_601.jpg](https://github.com/user-attachments/assets/71b7a74c-554f-4138-8503-0ea292dd6b18)

**Comment by JSDID** [comment]
![IMG_20241207_132506_610.jpg](https://github.com/user-attachments/assets/7e95fcab-995b-481a-9118-19d5332ccf64)

![IMG_20241207_132510_601.jpg](https://github.com/user-attachments/assets/f92e5466-b164-4cec-924c-475fe6f9ddc7)

**Comment by kamabzalov** [comment]
@JSDID речь про фильтрацию и пагинацию - читайте внимательно задачу еще раз

**Comment by JSDID** [comment]
> @JSDID речь про фильтрацию и пагинацию - читайте внимательно задачу еще раз

Контактах такая Фильтрация и Пагинация 

![IMG_20241207_134248_443.jpg](https://github.com/user-attachments/assets/48a57061-06ea-4344-b19d-d03265083b07)

**Comment by JSDID** [comment]
![IMG_20241207_134521_091.jpg](https://github.com/user-attachments/assets/0c1f83d2-562b-44e9-88a0-85154f46fc08)

**Comment by kamabzalov** [comment]
В инвентории есть парамтер page - откуда он?

**Comment by JSDID** [comment]
> В инвентории есть парамтер page и first - откуда они?

Они добавляются я вижу когда мы в Advances search выбираем Make

**Comment by kamabzalov** [comment]
> > В инвентории есть парамтер page и first - откуда они?
> 
> Они добавляются я вижу когда мы в Advances search выбираем Make

А в обычном поиске (в таблице и пр)?

**Comment by JSDID** [comment]
> > > В инвентории есть парамтер page и first - откуда они?
> > 
> > Они добавляются я вижу когда мы в Advances search выбираем Make
> 
> А в обычном поиске (в таблице и пр)?

При фильтрации и пагинации не было.  Контах не добавляется.

**Comment by kamabzalov** [comment]
@JSDID Зачем нам пагинация в advanced search - где вы ее там видите?

**Comment by kamabzalov** [comment]
При фильтрации вот такая строка формируется (в таблице по статусу как пример)

https://app.admss.com/api/v1/inventory/33e88d0e-fa44-4e1d-a279-e8a72f9bbbbb/list?skip=100&top=20&qry=sold.Status

У вас какие-то странные поля в Advanced search

**Comment by JSDID** [comment]
![IMG_20241207_144513_954.jpg](https://github.com/user-attachments/assets/242a84eb-7f33-417e-bfc2-8a30eaec48ba)

**Comment by kamabzalov** [comment]
Вас в задаче спрашивают - что это за параметры??
[first=0&rows=1000&page=1&sortField=Make&sortOrder=1](https://app.admss.com/api/v1/inventory/57b60d65-1eed-4fdf-80d8-02fdcc45bbe7/list?first=0&rows=1000&page=1&sortField=Make&sortOrder=1&qry=BMW.Make%27)

**Comment by kamabzalov** [comment]
я их тоже нигде в приложении не вижу - только в Advanced search inventory

**Comment by JSDID** [comment]
Мы формировали согласно инструкций. Я же его не с головы брал. Все фильтры, поиски сделаны согласно инструкций бека

В старых задачах. Их найти сейчас очень трудно будет. Они внутри задач, в коментариях.

Текущую страницу из запроса можно убрать, а количество записей оставить на основе того значения, что стоит сейчас.

Сортировка стоит последняя, которая была задана пользователем для таблицы. Ее тоже убрать?

**Comment by JSDID** [comment]
Убрал лишние запросы и пофиксил лишний запрос при инициализации.
