### ISSUE TITLE
Advanced search in contact

### ISSUE THREAD

**Issue by kamabzalov** [kamabzalov/admss-client#783]
Если вставить номер телефона через ctrl V, то он как будто его не видит и не активирует кнопку поисковика

**Comment by kamabzalov** [comment]
@JSDID уберите 1 в поиске по телефону

**Comment by JSDID** [comment]
> @JSDID уберите 1 в поиске по телефону

Что значить убрать 1?

**Comment by JSDID** [comment]
> @JSDID [/list?qry=4444444444.phone1'](https://app.admss.com/api/v1/contacts/d51ffe3a-10d3-497e-a4d2-61894dae2b2e/list?qry=4444444444.phone1%27) вы ищете по phone1, а надо по phone

https://github.com/kamabzalov/admss-client/issues/766#issuecomment-2509169296

сказано было искать по phone1

**Comment by kamabzalov** [comment]
@JSDID ну сейчас просят поменять
